export interface DayActivity {
  time: string;
  activity: string;
  description: string;
  icon: string;
}

export interface ItineraryDay {
  day: number;
  title: string;
  location: string;
  activities: DayActivity[];
  accommodation: string;
  meals: string[];
}

export interface PackagePrice {
  provider: string;
  price: number;
  duration: string;
  inclusions: string[];
  rating: number;
  reviewCount: number;
  departureDates: string[];
  url: string;
  badge?: string;
}

export interface Destination {
  slug: string;
  name: string;
  country: string;
  flag: string;
  tagline: string;
  description: string;
  heroImage: string;
  duration: string;
  groupSize: string;
  difficulty: string;
  basePrice: number;
  highlights: string[];
  inclusions: string[];
  exclusions: string[];
  bestTime: string;
  itinerary: ItineraryDay[];
  comparison: PackagePrice[];
  gallery: string[];
  tags: string[];
  rating: number;
  reviewCount: number;
}

export const destinations: Destination[] = [
  {
    slug: "kerala",
    name: "Kerala",
    country: "India",
    flag: "🇮🇳",
    tagline: "God's Own Country",
    description:
      "Spend three days navigating the Kerala backwaters on a private houseboat, followed by guided walks through Munnar's high-altitude tea estates.",
    heroImage:
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1600&q=80",
    duration: "7 Days / 6 Nights",
    groupSize: "2–15 People",
    difficulty: "Easy",
    basePrice: 24999,
    rating: 4.8,
    reviewCount: 1247,
    bestTime: "October – March",
    tags: ["Backwaters", "Beaches", "Hill Stations", "Ayurveda"],
    highlights: [
      "Houseboat cruise on Alleppey backwaters",
      "Munnar tea estate walk",
      "Kathakali cultural show",
      "Kovalam beach sunset",
      "Periyar wildlife sanctuary",
      "Traditional Kerala fish curry cooking class",
    ],
    inclusions: [
      "6 nights accommodation (deluxe hotels + 1 night houseboat)",
      "Daily breakfast and dinner",
      "All transfers in AC vehicle",
      "Houseboat cruise (full day)",
      "English-speaking guide",
      "Periyar nature walk",
      "All entry fees",
    ],
    exclusions: [
      "Airfare / train tickets",
      "Personal expenses",
      "Travel insurance",
      "Lunch",
      "Tips and gratuities",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival in Kochi – Spice Capital",
        location: "Kochi",
        activities: [
          { time: "10:00 AM", activity: "Airport Pickup", description: "Meet & greet at Cochin International Airport", icon: "plane" },
          { time: "12:00 PM", activity: "Hotel Check-in", description: "Check in to your heritage hotel in Fort Kochi", icon: "hotel" },
          { time: "2:00 PM", activity: "Fort Kochi Walk", description: "Explore the iconic Chinese fishing nets, St. Francis Church & Mattancherry Palace", icon: "map" },
          { time: "6:30 PM", activity: "Kathakali Show", description: "Evening classical Kathakali dance performance", icon: "music" },
          { time: "8:00 PM", activity: "Kerala Dinner", description: "Traditional Kerala sadya served on banana leaf", icon: "utensils" },
        ],
        accommodation: "Brunton Boatyard Heritage Hotel, Kochi",
        meals: ["Dinner"],
      },
      {
        day: 2,
        title: "Munnar – The Tea Hills",
        location: "Munnar",
        activities: [
          { time: "8:00 AM", activity: "Breakfast & Departure", description: "Drive to Munnar through scenic Western Ghats (4 hrs)", icon: "bus" },
          { time: "12:30 PM", activity: "Cheeyappara Waterfalls", description: "Stop at the stunning cascading waterfalls", icon: "waves" },
          { time: "2:00 PM", activity: "Tea Museum", description: "Learn about Kerala's tea heritage at Tata Tea Museum", icon: "coffee" },
          { time: "4:00 PM", activity: "Tea Plantation Walk", description: "Guided walk through lush green tea estates", icon: "leaf" },
          { time: "7:30 PM", activity: "Sunset Viewpoint", description: "Watch the golden sunset over the misty mountains", icon: "sunset" },
        ],
        accommodation: "Windermere Estate, Munnar",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 3,
        title: "Thekkady – Wild Encounters",
        location: "Thekkady",
        activities: [
          { time: "7:00 AM", activity: "Morning Nature Walk", description: "Early morning bird watching in Eravikulam National Park", icon: "bird" },
          { time: "10:00 AM", activity: "Drive to Thekkady", description: "2.5 hour drive through spice country", icon: "bus" },
          { time: "1:30 PM", activity: "Spice Garden Tour", description: "Visit cardamom & pepper plantations with guided tour", icon: "leaf" },
          { time: "3:30 PM", activity: "Periyar Boat Ride", description: "Boat safari on Periyar Lake spotting wildlife", icon: "ship" },
          { time: "7:00 PM", activity: "Kalaripayattu Show", description: "Watch Kerala's ancient martial art performance", icon: "swords" },
        ],
        accommodation: "Spice Village, Thekkady",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 4,
        title: "Alleppey – Backwater Paradise",
        location: "Alleppey",
        activities: [
          { time: "9:00 AM", activity: "Drive to Alleppey", description: "3-hour scenic drive to the Venice of the East", icon: "bus" },
          { time: "12:30 PM", activity: "Houseboat Check-in", description: "Board your luxurious traditional Kerala houseboat (Kettuvallam)", icon: "ship" },
          { time: "1:30 PM", activity: "Backwater Cruise", description: "Float through tranquil backwaters, rice paddies, and villages", icon: "waves" },
          { time: "4:00 PM", activity: "Village Visit", description: "Stop at a local village, coir-making demonstration", icon: "home" },
          { time: "7:30 PM", activity: "Sunset Dinner", description: "Fresh seafood dinner on deck as the sun sets over the lagoon", icon: "utensils" },
        ],
        accommodation: "Luxury Houseboat, Alleppey Backwaters",
        meals: ["Breakfast", "Lunch", "Dinner"],
      },
      {
        day: 5,
        title: "Kovalam – Beach Bliss",
        location: "Kovalam",
        activities: [
          { time: "7:30 AM", activity: "Sunrise on the Backwaters", description: "Watch the magical sunrise over the water from your houseboat deck", icon: "sunrise" },
          { time: "9:00 AM", activity: "Drive to Kovalam", description: "3.5 hour drive to the beach capital of Kerala", icon: "bus" },
          { time: "1:00 PM", activity: "Beach Time", description: "Relax on the crescent-shaped Kovalam beach", icon: "umbrella" },
          { time: "3:30 PM", activity: "Ayurvedic Massage", description: "Traditional Kerala Abhyanga full body massage (90 min)", icon: "flower" },
          { time: "7:00 PM", activity: "Seafood Dinner", description: "Fresh catch at a beachside restaurant with ocean view", icon: "fish" },
        ],
        accommodation: "Turtle Bay Beach Club, Kovalam",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 6,
        title: "Trivandrum – Culture & History",
        location: "Thiruvananthapuram",
        activities: [
          { time: "9:00 AM", activity: "Padmanabhaswamy Temple", description: "Visit one of India's richest and most sacred temples", icon: "landmark" },
          { time: "11:30 AM", activity: "Napier Museum", description: "Explore Kerala's art, natural history & tribal artifacts", icon: "building" },
          { time: "2:00 PM", activity: "Kuthiramalika Palace", description: "Tour the royal palace with 122 horse-shaped brackets", icon: "crown" },
          { time: "4:30 PM", activity: "Shankumugham Beach", description: "Walk along the beach with views of the sunset", icon: "sunset" },
          { time: "7:30 PM", activity: "Farewell Kerala Dinner", description: "Special goodbye dinner with cultural music performance", icon: "music" },
        ],
        accommodation: "The Leela Palace, Trivandrum",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 7,
        title: "Departure Day",
        location: "Thiruvananthapuram",
        activities: [
          { time: "8:00 AM", activity: "Final Breakfast", description: "Last Kerala breakfast with appam and stew", icon: "coffee" },
          { time: "10:00 AM", activity: "Hotel Check-out", description: "Check out and transfer to Trivandrum International Airport", icon: "hotel" },
          { time: "12:00 PM", activity: "Airport Drop", description: "Fond farewell and departure from God's Own Country", icon: "plane" },
        ],
        accommodation: "",
        meals: ["Breakfast"],
      },
    ],
    comparison: [
      {
        provider: "WanderSouls",
        price: 24999,
        duration: "7D/6N",
        inclusions: ["6N Deluxe Hotels + Houseboat", "Breakfast & Dinner", "AC Transfers", "Guide", "Entry Fees", "Ayurvedic Session"],
        rating: 4.8,
        reviewCount: 1247,
        departureDates: ["Jun 15", "Jul 1", "Jul 15", "Aug 1"],
        url: "#",
        badge: "Best Value",
      },
      {
        provider: "Veena World",
        price: 31500,
        duration: "7D/6N",
        inclusions: ["6N Standard Hotels + Houseboat", "Breakfast Only", "AC Transfers", "Guide"],
        rating: 4.3,
        reviewCount: 842,
        departureDates: ["Jun 20", "Jul 5", "Aug 10"],
        url: "https://www.veenaworld.com/india/kerala-tour-packages",
      },
      {
        provider: "MakeMyTrip",
        price: 28750,
        duration: "7D/6N",
        inclusions: ["6N Hotels", "Breakfast Only", "Shared Transfers", "No Guide"],
        rating: 4.1,
        reviewCount: 2103,
        departureDates: ["Jun 10", "Jun 25", "Jul 20", "Aug 5"],
        url: "https://www.makemytrip.com/holidays-india/kerala-travel-packages.html",
      },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
      "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&q=80",
      "https://images.unsplash.com/photo-1595385771900-14c2d8b1f99c?w=800&q=80",
    ],
  },
  {
    slug: "thailand",
    name: "Thailand",
    country: "Thailand",
    flag: "🇹🇭",
    tagline: "Land of Smiles",
    description:
      "Navigate Bangkok's local food markets with our resident guides, then fly south for five days of private boat charters around the Phi Phi islands.",
    heroImage:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&q=80",
    duration: "8 Days / 7 Nights",
    groupSize: "2–20 People",
    difficulty: "Easy",
    basePrice: 39999,
    rating: 4.9,
    reviewCount: 2158,
    bestTime: "November – April",
    tags: ["Temples", "Beaches", "Street Food", "Nightlife", "Islands"],
    highlights: [
      "Grand Palace & Wat Phra Kaew",
      "Chiang Mai Night Bazaar & temples",
      "Elephant Nature Park encounter",
      "Phi Phi Islands speedboat tour",
      "Thai cooking class",
      "Floating Market",
    ],
    inclusions: [
      "7 nights accommodation (mix of Bangkok, Chiang Mai & Phuket)",
      "Daily breakfast",
      "All inter-city flights (BKK-CNX-HKT)",
      "Airport & hotel transfers",
      "English-speaking guide",
      "Phi Phi island tour",
      "Thai cooking class",
      "All entry fees",
    ],
    exclusions: [
      "International airfare",
      "Travel insurance",
      "Lunch and dinner",
      "Personal expenses",
      "Visa fees (if applicable)",
    ],
    itinerary: [
      {
        day: 1,
        title: "Welcome to Bangkok",
        location: "Bangkok",
        activities: [
          { time: "12:00 PM", activity: "Arrival & Hotel Check-in", description: "Arrive at Suvarnabhumi Airport, transfer to Sukhumvit hotel", icon: "plane" },
          { time: "3:00 PM", activity: "Wat Pho & Reclining Buddha", description: "Visit the iconic 46-metre gold reclining Buddha", icon: "landmark" },
          { time: "5:30 PM", activity: "Chao Phraya River Cruise", description: "Sunset cruise along the River of Kings", icon: "ship" },
          { time: "8:00 PM", activity: "Khao San Road & Street Food", description: "Explore the legendary backpacker street with amazing street food", icon: "utensils" },
        ],
        accommodation: "Chatrium Hotel Riverside Bangkok",
        meals: ["Dinner"],
      },
      {
        day: 2,
        title: "Bangkok – Temples & Markets",
        location: "Bangkok",
        activities: [
          { time: "8:00 AM", activity: "Grand Palace & Wat Phra Kaew", description: "Explore Thailand's most sacred site with the Emerald Buddha", icon: "crown" },
          { time: "11:00 AM", activity: "Floating Market", description: "Damnoen Saduak – colourful boats selling local produce", icon: "shopping-bag" },
          { time: "2:00 PM", activity: "Wat Arun", description: "Cross the river to the Temple of Dawn – breathtaking views", icon: "sunset" },
          { time: "5:00 PM", activity: "Chatuchak Weekend Market", description: "World's largest weekend market (over 15,000 stalls)", icon: "shopping-cart" },
          { time: "8:00 PM", activity: "Rooftop Bar", description: "Cocktails with Bangkok skyline views at Sky Bar", icon: "glass-water" },
        ],
        accommodation: "Chatrium Hotel Riverside Bangkok",
        meals: ["Breakfast"],
      },
      {
        day: 3,
        title: "Chiang Mai – Rose of the North",
        location: "Chiang Mai",
        activities: [
          { time: "7:00 AM", activity: "Flight to Chiang Mai", description: "1-hour domestic flight to Chiang Mai Airport", icon: "plane" },
          { time: "10:30 AM", activity: "Old City Walking Tour", description: "Explore the ancient moat-surrounded old city and Tha Phae Gate", icon: "map" },
          { time: "2:00 PM", activity: "Doi Suthep Temple", description: "Sacred hilltop temple with panoramic city views (climb 300 steps!)", icon: "landmark" },
          { time: "5:00 PM", activity: "Night Bazaar", description: "Shop for handicrafts, silks & silver at the famous night market", icon: "moon" },
          { time: "7:30 PM", activity: "Khantoke Dinner", description: "Traditional northern Thai dinner with classical dance show", icon: "music" },
        ],
        accommodation: "Dhara Dhevi Chiang Mai",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 4,
        title: "Elephant Sanctuary & Cooking Class",
        location: "Chiang Mai",
        activities: [
          { time: "8:30 AM", activity: "Elephant Nature Park", description: "Full morning at ethical elephant sanctuary – feed, bathe & walk with elephants", icon: "camera" },
          { time: "1:00 PM", activity: "Lunch & Market Visit", description: "Visit a local organic market to pick fresh ingredients", icon: "leaf" },
          { time: "3:00 PM", activity: "Thai Cooking Class", description: "Learn to cook 4 authentic Thai dishes with a local chef", icon: "chef-hat" },
          { time: "7:00 PM", activity: "Lantern Ceremony", description: "Release a Khom Loi sky lantern (seasonal)", icon: "lantern" },
        ],
        accommodation: "Dhara Dhevi Chiang Mai",
        meals: ["Breakfast", "Lunch"],
      },
      {
        day: 5,
        title: "Phuket – Island Paradise",
        location: "Phuket",
        activities: [
          { time: "8:00 AM", activity: "Flight to Phuket", description: "Domestic flight from Chiang Mai to Phuket Airport", icon: "plane" },
          { time: "11:30 AM", activity: "Patong Beach", description: "Spend the afternoon on Thailand's most famous beach", icon: "umbrella" },
          { time: "4:00 PM", activity: "Big Buddha", description: "Visit the 45-metre marble Buddha with sweeping island views", icon: "user" },
          { time: "7:00 PM", activity: "Bangla Road", description: "Explore Phuket's vibrant nightlife and street performances", icon: "tent" },
        ],
        accommodation: "Katathani Phuket Beach Resort",
        meals: ["Breakfast"],
      },
      {
        day: 6,
        title: "Phi Phi Islands Speedboat Tour",
        location: "Phi Phi Islands",
        activities: [
          { time: "8:00 AM", activity: "Speedboat to Phi Phi", description: "45-min speedboat ride to paradise islands", icon: "ship" },
          { time: "9:30 AM", activity: "Maya Bay", description: "Visit the famous 'The Beach' movie location (limited access)", icon: "tree-palm" },
          { time: "11:00 AM", activity: "Snorkelling", description: "Coral reefs with tropical fish in crystal waters", icon: "waves" },
          { time: "1:00 PM", activity: "Lunch on Phi Phi Don", description: "Fresh seafood BBQ on the beach", icon: "fish" },
          { time: "3:00 PM", activity: "Viking Cave & Monkey Bay", description: "Explore ancient Viking cave paintings and meet cheeky monkeys", icon: "camera" },
          { time: "5:00 PM", activity: "Return to Phuket", description: "Speedboat back to Phuket with sunset views", icon: "sunset" },
        ],
        accommodation: "Katathani Phuket Beach Resort",
        meals: ["Breakfast", "Lunch"],
      },
      {
        day: 7,
        title: "Phuket – Leisure & Spa",
        location: "Phuket",
        activities: [
          { time: "9:00 AM", activity: "Karon Beach", description: "Morning at the less crowded beautiful Karon Beach", icon: "waves" },
          { time: "12:00 PM", activity: "Thai Massage", description: "2-hour traditional Thai massage at a luxury spa", icon: "flower" },
          { time: "3:00 PM", activity: "Phuket Old Town", description: "Explore Sino-Portuguese architecture and colourful shophouses", icon: "home" },
          { time: "7:30 PM", activity: "Farewell Thai Dinner", description: "Premium Thai seafood dinner on the beach", icon: "fish" },
        ],
        accommodation: "Katathani Phuket Beach Resort",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 8,
        title: "Departure from Phuket",
        location: "Phuket",
        activities: [
          { time: "9:00 AM", activity: "Final Breakfast", description: "Last Thai breakfast at the resort", icon: "coffee" },
          { time: "11:00 AM", activity: "Check-out & Transfer", description: "Hotel check-out and transfer to Phuket International Airport", icon: "bus" },
          { time: "2:00 PM", activity: "Departure", description: "Board your international flight home, khob khun krap!", icon: "plane" },
        ],
        accommodation: "",
        meals: ["Breakfast"],
      },
    ],
    comparison: [
      {
        provider: "WanderSouls",
        price: 39999,
        duration: "8D/7N",
        inclusions: ["7N Premium Hotels", "Daily Breakfast", "3 Domestic Flights", "Island Tour", "Elephant Sanctuary", "Cooking Class", "All Transfers"],
        rating: 4.9,
        reviewCount: 2158,
        departureDates: ["Jun 12", "Jul 3", "Jul 17", "Aug 7"],
        url: "#",
        badge: "Most Popular",
      },
      {
        provider: "Veena World",
        price: 52499,
        duration: "8D/7N",
        inclusions: ["7N Standard Hotels", "Breakfast", "2 Domestic Flights", "Island Tour", "Transfers"],
        rating: 4.4,
        reviewCount: 1203,
        departureDates: ["Jun 18", "Jul 9", "Aug 2"],
        url: "https://www.veenaworld.com/thailand-tour-packages",
      },
      {
        provider: "MakeMyTrip",
        price: 47081,
        duration: "8D/7N",
        inclusions: ["7N Hotels", "Breakfast", "2 Domestic Flights", "No Island Tour", "Shared Transfers"],
        rating: 4.2,
        reviewCount: 3412,
        departureDates: ["Jun 5", "Jun 22", "Jul 10", "Aug 15"],
        url: "https://www.makemytrip.com/holidays-international/7nights-thailand-vacation-tour-package.html",
      },
    ],
    gallery: [
      "/gallery/thailand/AyutthayaElephant.jpg",
      "/gallery/thailand/mayabay.jpg",
      "/gallery/thailand/WatArun.jpg",
      "/gallery/thailand/reclining-buddha.jpg",
      "/gallery/thailand/wat-arun-2.jpg",
      "/gallery/thailand/wat-arun_edited.jpg",
    ],
  },
  {
    slug: "philippines",
    name: "Philippines",
    country: "Philippines",
    flag: "🇵🇭",
    tagline: "More Than the Expected",
    description:
      "A seven-day expedition through Palawan. Expect private island-hopping out of El Nido, guided snorkeling, and quiet beach stays.",
    heroImage:
      "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=1600&q=80",
    duration: "8 Days / 7 Nights",
    groupSize: "2–16 People",
    difficulty: "Moderate",
    basePrice: 44999,
    rating: 4.7,
    reviewCount: 876,
    bestTime: "December – May",
    tags: ["Islands", "Diving", "Beaches", "Nature", "Adventure"],
    highlights: [
      "Coron island hopping & diving",
      "Puerto Princesa Underground River",
      "El Nido lagoons & limestone karsts",
      "Chocolate Hills Bohol",
      "Tarsier Sanctuary",
      "Boracay White Beach sunset",
    ],
    inclusions: [
      "7 nights accommodation",
      "Daily breakfast",
      "All island hopping tours",
      "Underground river tour",
      "Domestic flights & ferry transfers",
      "English guide",
      "Snorkelling gear",
    ],
    exclusions: [
      "International airfare",
      "Travel insurance",
      "Lunch & dinner",
      "Diving equipment",
      "Visa fees",
    ],
    itinerary: [
      {
        day: 1,
        title: "Manila – Gateway to Paradise",
        location: "Manila",
        activities: [
          { time: "2:00 PM", activity: "Arrival & Transfer", description: "Arrive at Ninoy Aquino International Airport, hotel transfer", icon: "plane" },
          { time: "4:00 PM", activity: "Intramuros Tour", description: "Explore the historic Spanish walled city on a bamboo bike", icon: "bike" },
          { time: "7:00 PM", activity: "Manila Sunset Cruise", description: "Manila Bay sunset cruise — world famous golden sunsets", icon: "sunset" },
          { time: "8:30 PM", activity: "Filipino Feast", description: "Welcome dinner at a renowned Filipino restaurant", icon: "utensils" },
        ],
        accommodation: "Solaire Resort & Casino, Manila",
        meals: ["Dinner"],
      },
      {
        day: 2,
        title: "Palawan – El Nido Arrival",
        location: "El Nido, Palawan",
        activities: [
          { time: "6:00 AM", activity: "Flight to El Nido", description: "Early morning flight from Manila to El Nido Airport", icon: "plane" },
          { time: "10:30 AM", activity: "El Nido Town Explore", description: "Settle in and explore El Nido town's colourful market", icon: "home" },
          { time: "2:00 PM", activity: "Nacpan Beach", description: "Afternoon at one of the world's top 10 beaches", icon: "umbrella" },
          { time: "7:00 PM", activity: "Clifftop Dinner", description: "Dinner with panoramic views over the Bacuit Bay", icon: "star" },
        ],
        accommodation: "El Nido Resorts Lagen Island",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 3,
        title: "El Nido Island Hopping Tour A",
        location: "El Nido, Palawan",
        activities: [
          { time: "8:30 AM", activity: "Boat Departure", description: "Start the iconic Tour A island hopping route", icon: "ship" },
          { time: "9:30 AM", activity: "Big Lagoon", description: "Kayak through the stunning big lagoon between limestone karsts", icon: "ship" },
          { time: "11:00 AM", activity: "Small Lagoon", description: "Swim through the secret small lagoon – emerald paradise", icon: "waves" },
          { time: "12:30 PM", activity: "Shimizu Island Lunch", description: "BBQ seafood lunch on pristine white sand", icon: "fish" },
          { time: "2:30 PM", activity: "Seven Commandos Beach", description: "Snorkel at the coral garden, laze on white sand", icon: "waves" },
          { time: "5:00 PM", activity: "Return to El Nido", description: "Sunset boat ride back to town", icon: "sunset" },
        ],
        accommodation: "El Nido Resorts Lagen Island",
        meals: ["Breakfast", "Lunch"],
      },
      {
        day: 4,
        title: "Underground River – UNESCO Wonder",
        location: "Puerto Princesa",
        activities: [
          { time: "6:00 AM", activity: "Drive to Port Barton", description: "Scenic drive through Palawan jungle (2 hrs)", icon: "leaf" },
          { time: "9:00 AM", activity: "Sabang Beach", description: "Brief stop at jungle-meets-beach paradise", icon: "🏝️" },
          { time: "10:30 AM", activity: "Underground River Tour", description: "Paddle through the world's longest navigable underground river (UNESCO)", icon: "camera" },
          { time: "1:00 PM", activity: "Jungle Lunch", description: "Fresh lunch amid the jungle with wildlife spotting", icon: "camera" },
          { time: "4:00 PM", activity: "Drive to Puerto Princesa", description: "Return drive to the city (2 hrs)", icon: "bus" },
          { time: "7:00 PM", activity: "Seafood Market Dinner", description: "Pick your fresh seafood and have it grilled right there", icon: "fish" },
        ],
        accommodation: "Astoria Palawan, Puerto Princesa",
        meals: ["Breakfast", "Lunch", "Dinner"],
      },
      {
        day: 5,
        title: "Bohol – Chocolate Hills & Tarsiers",
        location: "Bohol",
        activities: [
          { time: "7:00 AM", activity: "Flight to Bohol", description: "Morning flight to Tagbilaran Airport, Bohol", icon: "plane" },
          { time: "10:00 AM", activity: "Tarsier Sanctuary", description: "Visit the world's smallest primates at the Philippine Tarsier Sanctuary", icon: "camera" },
          { time: "12:00 PM", activity: "Chocolate Hills", description: "Over 1,200 symmetrical grass-covered hills — marvel at nature's geometry", icon: "mountain" },
          { time: "2:30 PM", activity: "Loboc River Cruise", description: "Floating restaurant cruise on the scenic Loboc River with cultural show", icon: "ship" },
          { time: "5:00 PM", activity: "Panglao Island Transfer", description: "Head to the beach paradise of Panglao", icon: "bus" },
        ],
        accommodation: "Amorita Resort, Panglao Island",
        meals: ["Breakfast", "Lunch"],
      },
      {
        day: 6,
        title: "Panglao – Diving & Beach",
        location: "Panglao Island, Bohol",
        activities: [
          { time: "8:00 AM", activity: "Alona Beach", description: "Morning at the famous Alona Beach – world-class snorkelling", icon: "waves" },
          { time: "10:00 AM", activity: "Balicasag Island Dive", description: "Dive or snorkel with sea turtles at Balicasag Marine Sanctuary", icon: "🐢" },
          { time: "1:00 PM", activity: "Island Lunch", description: "Fresh lunch on a sandbar with 360° ocean views", icon: "fish" },
          { time: "3:00 PM", activity: "Free Beach Time", description: "Relax, swim, parasail or try water sports", icon: "waves" },
          { time: "7:00 PM", activity: "Beachside Dinner", description: "Grilled fish and local lechon under the stars", icon: "flame" },
        ],
        accommodation: "Amorita Resort, Panglao Island",
        meals: ["Breakfast", "Lunch", "Dinner"],
      },
      {
        day: 7,
        title: "Boracay – White Beach Finale",
        location: "Boracay",
        activities: [
          { time: "9:00 AM", activity: "Ferry + Flight to Boracay", description: "Transfer to Caticlan and take the short boat to Boracay", icon: "ship" },
          { time: "12:30 PM", activity: "White Beach", description: "World-famous 4km white powder beach — afternoon leisure", icon: "tree-palm" },
          { time: "4:00 PM", activity: "Paraw Sailing", description: "Traditional Filipino outrigger sunset sail", icon: "ship" },
          { time: "6:30 PM", activity: "Sunset at D'Mall", description: "Shop, browse, and watch the legendary Boracay sunset", icon: "sunset" },
          { time: "8:00 PM", activity: "Farewell Beach Party", description: "Fire dancers, beach BBQ & cocktails under the stars", icon: "party-popper" },
        ],
        accommodation: "Movenpick Resort Boracay",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 8,
        title: "Departure",
        location: "Manila",
        activities: [
          { time: "8:00 AM", activity: "Breakfast & Check-out", description: "Final breakfast and hotel check-out", icon: "coffee" },
          { time: "10:00 AM", activity: "Flight to Manila", description: "Return flight from Caticlan/Kalibo to Manila", icon: "plane" },
          { time: "2:00 PM", activity: "Departure", description: "Departure from Ninoy Aquino International Airport", icon: "plane" },
        ],
        accommodation: "",
        meals: ["Breakfast"],
      },
    ],
    comparison: [
      {
        provider: "WanderSouls",
        price: 44999,
        duration: "8D/7N",
        inclusions: ["7N Premium Hotels", "Daily Breakfast", "All Domestic Flights & Ferries", "All Island Tours", "Underground River", "Diving/Snorkelling", "Guide"],
        rating: 4.7,
        reviewCount: 876,
        departureDates: ["Jun 8", "Jun 28", "Jul 18", "Aug 8"],
        url: "#",
        badge: "Best Value",
      },
      {
        provider: "Veena World",
        price: 98500,
        duration: "8D/7N",
        inclusions: ["7N Standard Hotels", "Breakfast", "3 Domestic Flights", "2 Island Tours", "No Diving"],
        rating: 4.3,
        reviewCount: 421,
        departureDates: ["Jun 14", "Jul 5", "Aug 12"],
        url: "https://www.veenaworld.com/philippines-tour-packages",
      },
      {
        provider: "MakeMyTrip",
        price: 105000,
        duration: "8D/7N",
        inclusions: ["7N Hotels", "Breakfast", "2 Domestic Flights", "1 Island Tour", "Shared Transfers"],
        rating: 4.0,
        reviewCount: 1564,
        departureDates: ["Jun 1", "Jun 20", "Jul 15", "Aug 10"],
        url: "https://www.makemytrip.com/holidays-international/philippines-tour-packages.html",
      },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&q=80",
      "https://images.unsplash.com/photo-1503917988258-f87a78e3c995?w=800&q=80",
    ],
  },
  {
    slug: "singapore",
    name: "Singapore",
    country: "Singapore",
    flag: "🇸🇬",
    tagline: "The Lion City",
    description:
      "Four nights in the city center. We balance the main attractions with private food tours through the local hawker centers and early access to the Gardens by the Bay.",
    heroImage:
      "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1600&q=80",
    duration: "5 Days / 4 Nights",
    groupSize: "2–20 People",
    difficulty: "Easy",
    basePrice: 54999,
    rating: 4.8,
    reviewCount: 1876,
    bestTime: "February – April",
    tags: ["City", "Food", "Shopping", "Architecture", "Culture"],
    highlights: [
      "Gardens by the Bay & Supertrees",
      "Marina Bay Sands SkyPark",
      "Sentosa Island & Universal Studios",
      "Hawker Centre food tour",
      "Little India & Chinatown",
      "Night Safari",
    ],
    inclusions: [
      "4 nights luxury hotel",
      "Daily breakfast",
      "MRT card (loaded)",
      "Gardens by the Bay tickets",
      "Night Safari tickets",
      "Universal Studios tickets",
      "City food tour",
      "Airport transfers",
    ],
    exclusions: [
      "International airfare",
      "Lunch & dinner (except food tour)",
      "Travel insurance",
      "Personal expenses",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival – Lion City Welcome",
        location: "Singapore",
        activities: [
          { time: "2:00 PM", activity: "Changi Airport Arrival", description: "Arrive at Changi — voted world's best airport. Explore Jewel waterfall!", icon: "plane" },
          { time: "4:00 PM", activity: "Hotel Check-in", description: "Check in to your Marina Bay luxury hotel", icon: "hotel" },
          { time: "6:00 PM", activity: "Marina Bay Sands SkyPark", description: "Sunset views from 57 floors up at the iconic infinity pool terrace", icon: "building" },
          { time: "8:00 PM", activity: "Spectra Light Show", description: "Free outdoor water and light spectacle at Marina Bay", icon: "sparkles" },
          { time: "9:00 PM", activity: "Clarke Quay", description: "Riverside dining and nightlife at Singapore's famous quayside", icon: "beer" },
        ],
        accommodation: "Marina Bay Sands Hotel",
        meals: ["Dinner"],
      },
      {
        day: 2,
        title: "Gardens, Culture & Heritage",
        location: "Singapore",
        activities: [
          { time: "9:00 AM", activity: "Gardens by the Bay", description: "Explore Cloud Forest, Flower Dome & the iconic Supertrees", icon: "leaf" },
          { time: "12:30 PM", activity: "Hawker Centre Food Tour", description: "Guided tour of Maxwell Food Centre — try 8+ signature dishes", icon: "utensils" },
          { time: "3:00 PM", activity: "Chinatown", description: "Buddha Tooth Relic Temple, heritage shophouses & souvenir shopping", icon: "lantern" },
          { time: "5:30 PM", activity: "Little India", description: "Colourful streets, garland stalls & the Sri Veeramakaliamman Temple", icon: "landmark" },
          { time: "8:00 PM", activity: "Arab Quarter", description: "Sultan Mosque & rooftop cocktails at Haji Lane", icon: "🕌" },
        ],
        accommodation: "Marina Bay Sands Hotel",
        meals: ["Breakfast", "Lunch"],
      },
      {
        day: 3,
        title: "Sentosa Island Adventure",
        location: "Sentosa Island, Singapore",
        activities: [
          { time: "9:00 AM", activity: "Universal Studios Singapore", description: "Full morning at USS – rides, shows & Hollywood adventures", icon: "ticket" },
          { time: "1:00 PM", activity: "Siloso Beach", description: "Afternoon at Sentosa's beach – swimming, volleyball, banana boats", icon: "umbrella" },
          { time: "4:00 PM", activity: "S.E.A. Aquarium", description: "One of the world's largest aquariums with 100,000+ marine animals", icon: "fish" },
          { time: "7:30 PM", activity: "Wings of Time", description: "Spectacular outdoor night show with water, laser & fireworks", icon: "sparkles" },
        ],
        accommodation: "Marina Bay Sands Hotel",
        meals: ["Breakfast"],
      },
      {
        day: 4,
        title: "Night Safari & Orchard Road",
        location: "Singapore",
        activities: [
          { time: "10:00 AM", activity: "Orchard Road Shopping", description: "Singapore's iconic 2.2km shopping paradise with 21 malls", icon: "shopping-bag" },
          { time: "1:00 PM", activity: "Botanic Gardens", description: "UNESCO World Heritage site – orchid garden & rainforest walk", icon: "flower" },
          { time: "4:00 PM", activity: "High Tea", description: "Quintessential Singapore afternoon high tea at Raffles Hotel", icon: "coffee" },
          { time: "7:30 PM", activity: "Night Safari", description: "World's first nocturnal zoo – see 2,500 animals under moonlight", icon: "camera" },
        ],
        accommodation: "Marina Bay Sands Hotel",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 5,
        title: "Final Morning & Departure",
        location: "Singapore",
        activities: [
          { time: "9:00 AM", activity: "Breakfast & Leisure", description: "Final breakfast and free time for last-minute shopping", icon: "coffee" },
          { time: "11:00 AM", activity: "Merlion Park", description: "Photo stop at Singapore's iconic Merlion statue", icon: "camera" },
          { time: "1:00 PM", activity: "Airport Transfer", description: "Transfer to Changi International Airport for departure", icon: "bus" },
        ],
        accommodation: "",
        meals: ["Breakfast"],
      },
    ],
    comparison: [
      {
        provider: "WanderSouls",
        price: 54999,
        duration: "5D/4N",
        inclusions: ["4N Marina Bay Sands Hotel", "Daily Breakfast", "All Attraction Tickets", "MRT Card", "Food Tour", "Airport Transfers"],
        rating: 4.8,
        reviewCount: 1876,
        departureDates: ["Jun 10", "Jun 24", "Jul 8", "Jul 22"],
        url: "#",
        badge: "Premium Pick",
      },
      {
        provider: "Veena World",
        price: 68499,
        duration: "5D/4N",
        inclusions: ["4N Standard Hotel", "Breakfast", "2 Attraction Tickets", "No Food Tour", "Airport Transfers"],
        rating: 4.5,
        reviewCount: 934,
        departureDates: ["Jun 15", "Jul 1", "Aug 5"],
        url: "https://www.veenaworld.com/singapore-tour-packages",
      },
      {
        provider: "MakeMyTrip",
        price: 52999,
        duration: "5D/4N",
        inclusions: ["4N Hotel", "Breakfast", "2 Attraction Tickets", "Shared Transfers"],
        rating: 4.2,
        reviewCount: 2841,
        departureDates: ["Jun 5", "Jun 19", "Jul 12", "Aug 2"],
        url: "https://www.makemytrip.com/holidays-international/singapore-tour-packages.html",
      },
    ],
    gallery: [
      "/gallery/singapore/singapore.jpg",
      "/gallery/singapore/SGfood.jpg",
      "/gallery/singapore/SGfood2.jpg",
      "/gallery/singapore/birdparkSG.jpg",
      "/gallery/singapore/universal.jpg",
      "/gallery/singapore/mike-enerio-7ryPpZK1qV8-unsplash.jpg",
      "/gallery/singapore/whatsapp-img-1.jpeg",
      "/gallery/singapore/whatsapp-img-2.jpeg",
      "/gallery/singapore/whatsapp-img-3.jpeg",
    ],
  },
  {
    slug: "south-africa",
    name: "South Africa",
    country: "South Africa",
    flag: "🇿🇦",
    tagline: "A World in One Country",
    description:
      "A ten-day cross-country route. Start with private game drives in Kruger before flying down to Cape Town for coastal routes and wine tasting.",
    heroImage:
      "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1600&q=80",
    duration: "10 Days / 9 Nights",
    groupSize: "2–12 People",
    difficulty: "Moderate",
    basePrice: 89999,
    rating: 4.9,
    reviewCount: 621,
    bestTime: "May – September",
    tags: ["Safari", "Wildlife", "Cape Town", "Winelands", "Adventure"],
    highlights: [
      "Kruger National Park Big 5 safari",
      "Cape Town & Table Mountain",
      "Winelands of Stellenbosch",
      "Cape of Good Hope",
      "Boulders Beach Penguins",
      "Robben Island & Nelson Mandela legacy",
    ],
    inclusions: [
      "9 nights accommodation (mix of safari lodges & city hotels)",
      "Full board at safari lodges, breakfast in cities",
      "2 domestic flights",
      "All game drives (morning + evening)",
      "Table Mountain cable car",
      "Cape Peninsula tour",
      "Winelands tour",
      "English ranger/guide",
    ],
    exclusions: [
      "International airfare",
      "Travel insurance",
      "Visa fees",
      "Tips for rangers and staff",
      "Personal purchases",
    ],
    itinerary: [
      {
        day: 1,
        title: "Johannesburg – Arrival",
        location: "Johannesburg",
        activities: [
          { time: "3:00 PM", activity: "OR Tambo Airport Arrival", description: "Land at Johannesburg, hotel transfer to Sandton", icon: "plane" },
          { time: "5:00 PM", activity: "Mandela Square", description: "Visit the famous Nelson Mandela statue in Sandton City", icon: "✊" },
          { time: "7:30 PM", activity: "South African Welcome Dinner", description: "Taste Braai (BBQ) and local South African wines", icon: "utensils" },
        ],
        accommodation: "Saxon Hotel, Villas & Spa, Johannesburg",
        meals: ["Dinner"],
      },
      {
        day: 2,
        title: "Soweto & Apartheid History",
        location: "Johannesburg / Soweto",
        activities: [
          { time: "9:00 AM", activity: "Apartheid Museum", description: "Powerful, moving account of South Africa's apartheid era", icon: "building" },
          { time: "12:00 PM", activity: "Soweto Township Tour", description: "Visit Mandela House, Hector Pieterson Museum & the community", icon: "home" },
          { time: "3:00 PM", activity: "Gold Reef City", description: "Descend into an old gold mine and learn about the gold rush", icon: "⚒️" },
          { time: "7:00 PM", activity: "Dinner at Neighbourgoods Market", description: "Artisanal food market with craft beers and gourmet bites", icon: "🍺" },
        ],
        accommodation: "Saxon Hotel, Villas & Spa, Johannesburg",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 3,
        title: "Kruger National Park – Into the Wild",
        location: "Kruger / Mpumalanga",
        activities: [
          { time: "7:00 AM", activity: "Blyde River Canyon", description: "En route to Kruger, stop at one of Africa's largest canyons", icon: "mountain" },
          { time: "12:00 PM", activity: "Bourke's Luck Potholes", description: "Extraordinary geological formations carved by rivers", icon: "droplet" },
          { time: "3:00 PM", activity: "Safari Lodge Check-in", description: "Check into your exclusive Kruger safari lodge", icon: "🏕️" },
          { time: "5:00 PM", activity: "Evening Game Drive", description: "First game drive — lions, elephants, rhinos!", icon: "camera" },
          { time: "7:30 PM", activity: "Bush Dinner", description: "Dinner under the African stars with a boma fire", icon: "flame" },
        ],
        accommodation: "Singita Sabi Sand Lodge, Kruger",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 4,
        title: "Kruger Safari – The Big 5",
        location: "Kruger National Park",
        activities: [
          { time: "5:30 AM", activity: "Morning Game Drive", description: "4-hour dawn game drive — best time to see big cats hunting", icon: "sunrise" },
          { time: "10:00 AM", activity: "Bush Walk", description: "Guided walking safari with a ranger — intimate wildlife encounter", icon: "🚶" },
          { time: "1:00 PM", activity: "Lodge Lunch & Rest", description: "Return for gourmet lunch and afternoon rest (it's Africa!)", icon: "😴" },
          { time: "4:30 PM", activity: "Sunset Game Drive", description: "Evening drive — hippos, leopards & stunning sunset on the bush", icon: "🦛" },
          { time: "8:00 PM", activity: "Star Gazing & Boma Dinner", description: "Ranger-led star gazing session, then dinner by the fire", icon: "⭐" },
        ],
        accommodation: "Singita Sabi Sand Lodge, Kruger",
        meals: ["Breakfast", "Lunch", "Dinner"],
      },
      {
        day: 5,
        title: "Cape Town – The Mother City",
        location: "Cape Town",
        activities: [
          { time: "9:00 AM", activity: "Flight to Cape Town", description: "Morning flight from Hoedspruit to Cape Town (2 hrs)", icon: "plane" },
          { time: "12:00 PM", activity: "V&A Waterfront", description: "Explore the vibrant harbour precinct with great restaurants & shops", icon: "⚓" },
          { time: "3:00 PM", activity: "Table Mountain", description: "Cable car to the top of the iconic flat-topped mountain", icon: "mountain" },
          { time: "7:00 PM", activity: "Long Street Explore", description: "Cape Town's legendary nightlife street with music & art", icon: "🎸" },
        ],
        accommodation: "The Silo Hotel, Cape Town",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 6,
        title: "Cape Peninsula – End of the World",
        location: "Cape Peninsula",
        activities: [
          { time: "8:30 AM", activity: "Boulders Beach Penguins", description: "Meet the famous African penguins at their beach colony", icon: "bird" },
          { time: "11:00 AM", activity: "Cape of Good Hope", description: "Stand at the southwestern tip of the African continent", icon: "🌍" },
          { time: "1:30 PM", activity: "Cape Point Lighthouse", description: "Hike up to the historic lighthouse for dramatic ocean views", icon: "building" },
          { time: "3:30 PM", activity: "Chapman's Peak Drive", description: "One of the world's most scenic coastal drives", icon: "🚗" },
          { time: "7:00 PM", activity: "Hout Bay Sunset Dinner", description: "Fresh seafood dinner overlooking the bay", icon: "fish" },
        ],
        accommodation: "The Silo Hotel, Cape Town",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 7,
        title: "Robben Island & Bo-Kaap",
        location: "Cape Town",
        activities: [
          { time: "9:00 AM", activity: "Robben Island Ferry", description: "Visit Mandela's prison cell — guided by ex-political prisoners", icon: "ship" },
          { time: "1:00 PM", activity: "Bo-Kaap", description: "Colourful Cape Malay quarter — colourful houses & spice aroma", icon: "🏠" },
          { time: "3:00 PM", activity: "Cape Town City Bowl", description: "Company's Garden, South African Museum & St George's Cathedral", icon: "🌳" },
          { time: "7:30 PM", activity: "Rooftop Dinner", description: "Dinner with panoramic views over Table Bay from the hotel", icon: "wine" },
        ],
        accommodation: "The Silo Hotel, Cape Town",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 8,
        title: "Stellenbosch Winelands",
        location: "Stellenbosch & Franschhoek",
        activities: [
          { time: "9:30 AM", activity: "Stellenbosch Town", description: "Walk through oak-lined streets of South Africa's wine capital", icon: "🍇" },
          { time: "11:00 AM", activity: "Delaire Graff Wine Estate", description: "World-class wine tasting with mountain backdrop & art gallery", icon: "wine" },
          { time: "1:00 PM", activity: "Wine Estate Lunch", description: "Gourmet lunch at one of the top wine farm restaurants", icon: "🥗" },
          { time: "3:00 PM", activity: "Franschhoek Wine Tram", description: "Hop-on hop-off wine tram through the beautiful valley", icon: "🚃" },
          { time: "6:00 PM", activity: "Sunset at Dieu Donné", description: "Final wine tasting as the sun sets over the mountains", icon: "sunrise" },
        ],
        accommodation: "The Silo Hotel, Cape Town",
        meals: ["Breakfast", "Lunch"],
      },
      {
        day: 9,
        title: "Leisure & Last Cape Town Day",
        location: "Cape Town",
        activities: [
          { time: "10:00 AM", activity: "Kalk Bay", description: "Charming fishing village with galleries, caves & markets", icon: "🎨" },
          { time: "12:30 PM", activity: "Camps Bay Beach", description: "Cape Town's glamorous beach with the Twelve Apostles backdrop", icon: "umbrella" },
          { time: "4:00 PM", activity: "Signal Hill Sunset Picnic", description: "Bring a blanket and watch the famous Cape Town sunset", icon: "sunset" },
          { time: "7:30 PM", activity: "Farewell Dinner", description: "Farewell dinner at a top Cape Town restaurant", icon: "wine" },
        ],
        accommodation: "The Silo Hotel, Cape Town",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 10,
        title: "Departure – Until Next Time, Africa",
        location: "Cape Town",
        activities: [
          { time: "9:00 AM", activity: "Final Breakfast", description: "Last South African breakfast with fresh rooibos tea", icon: "coffee" },
          { time: "11:00 AM", activity: "Airport Transfer", description: "Transfer to Cape Town International Airport", icon: "bus" },
          { time: "2:00 PM", activity: "Departure", description: "Farewell to the Rainbow Nation!", icon: "plane" },
        ],
        accommodation: "",
        meals: ["Breakfast"],
      },
    ],
    comparison: [
      {
        provider: "WanderSouls",
        price: 89999,
        duration: "10D/9N",
        inclusions: ["9N Premium Lodges & City Hotels", "Full Board Safari + Breakfast City", "2 Domestic Flights", "All Game Drives", "Peninsula Tour", "Winelands", "Guide"],
        rating: 4.9,
        reviewCount: 621,
        departureDates: ["Jun 20", "Jul 10", "Aug 1", "Sep 5"],
        url: "#",
        badge: "Editor's Choice",
      },
      {
        provider: "Veena World",
        price: 289000,
        duration: "10D/9N",
        inclusions: ["9N Standard Hotels & Lodges", "Breakfast + Safari Meals", "2 Domestic Flights", "Game Drives", "Peninsula Tour"],
        rating: 4.5,
        reviewCount: 283,
        departureDates: ["Jun 25", "Jul 15", "Aug 20"],
        url: "https://www.veenaworld.com/south-africa-tour-packages",
      },
      {
        provider: "MakeMyTrip",
        price: 249000,
        duration: "10D/9N",
        inclusions: ["9N Hotels & Lodge", "Breakfast Only", "1 Domestic Flight", "2 Game Drives", "No Winelands"],
        rating: 4.1,
        reviewCount: 892,
        departureDates: ["Jun 10", "Jul 5", "Aug 10"],
        url: "https://www.makemytrip.com/holidays-international/south-africa-tour-packages.html",
      },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&q=80",
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80",
    ],
  },
  {
    slug: "south-korea",
    name: "South Korea",
    country: "South Korea",
    flag: "🇰🇷",
    tagline: "Where Ancient Meets Ultra-Modern",
    description:
      "Explore the DMZ, Seoul's historic palaces, and the coastal city of Busan, wrapping up with two days of hiking and dining on Jeju Island.",
    heroImage: "/gallery/south-korea/sk_hero.png",
    duration: "7 Days / 6 Nights",
    groupSize: "2–18 People",
    difficulty: "Easy",
    basePrice: 49999,
    rating: 4.8,
    reviewCount: 1124,
    bestTime: "March – May / September – November",
    tags: ["K-Pop", "Temples", "City", "Street Food", "Cherry Blossoms"],
    highlights: [
      "Gyeongbokgung Palace & Hanbok experience",
      "DMZ tour at North Korean border",
      "Bukchon Hanok Village",
      "Busan BIFF Square & Haeundae Beach",
      "Jeju Island lava tubes & Hallasan",
      "Seoul street food tour & Night Market",
    ],
    inclusions: [
      "6 nights accommodation (Seoul, Busan & Jeju)",
      "Daily breakfast",
      "KTX bullet train (Seoul–Busan)",
      "Domestic flight (Busan–Jeju)",
      "DMZ tour",
      "Hanbok rental",
      "Seoul food tour",
      "Airport transfers",
    ],
    exclusions: [
      "International airfare",
      "Travel insurance",
      "Lunch & dinner",
      "K-Pop experience add-on",
      "Personal shopping expenses",
    ],
    itinerary: [
      {
        day: 1,
        title: "Seoul – First Impressions",
        location: "Seoul",
        activities: [
          { time: "1:00 PM", activity: "Incheon Airport Arrival", description: "Arrive at one of the world's busiest & best airports", icon: "plane" },
          { time: "3:30 PM", activity: "Myeongdong Street", description: "Korea's biggest shopping and street food district – instant ramen, egg bread, hot dogs!", icon: "🌭" },
          { time: "6:00 PM", activity: "Namsan Tower", description: "Cable car up N Seoul Tower for city panorama at dusk", icon: "landmark" },
          { time: "8:00 PM", activity: "Gangnam District", description: "Walk through the upscale Gangnam district — yes, that Gangnam!", icon: "🎵" },
        ],
        accommodation: "Park Hyatt Seoul",
        meals: ["Dinner"],
      },
      {
        day: 2,
        title: "Palaces, Hanboks & History",
        location: "Seoul",
        activities: [
          { time: "9:00 AM", activity: "Gyeongbokgung Palace", description: "Grand Joseon dynasty palace with changing of the guard ceremony", icon: "crown" },
          { time: "11:00 AM", activity: "Hanbok Experience", description: "Dress in traditional Korean costume and explore the palace grounds", icon: "👘" },
          { time: "1:00 PM", activity: "Bukchon Hanok Village", description: "500-year-old traditional hanok houses between two palaces", icon: "landmark" },
          { time: "3:30 PM", activity: "Insadong Alley", description: "Quirky street with galleries, traditional tea houses & crafts", icon: "🎨" },
          { time: "7:00 PM", activity: "Korean BBQ Dinner", description: "Grill galbi and samgyeopsal at a sizzling Korean BBQ restaurant", icon: "utensils" },
        ],
        accommodation: "Park Hyatt Seoul",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 3,
        title: "DMZ – North Korean Border",
        location: "Seoul / DMZ",
        activities: [
          { time: "8:00 AM", activity: "DMZ Tour Departs", description: "Full day tour to the Demilitarized Zone on the North Korean border", icon: "🪖" },
          { time: "10:00 AM", activity: "Imjingak Park", description: "Memorial park and Freedom Bridge over the Imjin River", icon: "🌉" },
          { time: "11:00 AM", activity: "Third Infiltration Tunnel", description: "Go underground into a tunnel North Korea dug toward Seoul", icon: "⛏️" },
          { time: "12:30 PM", activity: "Dora Observatory", description: "Look into North Korea through binoculars from the observation deck", icon: "🔭" },
          { time: "3:00 PM", activity: "Return to Seoul", description: "Return from the most tense border in the world", icon: "bus" },
          { time: "7:00 PM", activity: "Gwangjang Night Market", description: "Seoul's oldest market — bindaetteok pancakes & bibimbap", icon: "🥘" },
        ],
        accommodation: "Park Hyatt Seoul",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 4,
        title: "Busan – Korea's Beach City",
        location: "Busan",
        activities: [
          { time: "8:30 AM", activity: "KTX Bullet Train to Busan", description: "Board Korea's bullet train (280 km/h) — 2.5 hour journey", icon: "train" },
          { time: "11:30 AM", activity: "Gamcheon Culture Village", description: "Busan's dazzling colourful hillside village — art, murals, cafes", icon: "🎨" },
          { time: "2:00 PM", activity: "Jagalchi Fish Market", description: "Korea's largest seafood market — see live seafood being prepared", icon: "🐙" },
          { time: "4:00 PM", activity: "BIFF Square", description: "Walk the Busan International Film Festival famous footprints", icon: "🎬" },
          { time: "7:00 PM", activity: "Haeundae Beach Night", description: "Evening stroll along Korea's most famous beach", icon: "waves" },
        ],
        accommodation: "Westin Chosun Busan",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 5,
        title: "Busan Temples & Beaches",
        location: "Busan",
        activities: [
          { time: "9:00 AM", activity: "Haedong Yonggungsa Temple", description: "Stunning seaside Buddhist temple perched on sea cliffs", icon: "landmark" },
          { time: "11:00 AM", activity: "Haeundae Beach", description: "Morning on Korea's most famous sandy beach", icon: "umbrella" },
          { time: "1:30 PM", activity: "Gwangan Bridge View", description: "Lunch with views of the iconic twin-span suspension bridge", icon: "🌉" },
          { time: "4:00 PM", activity: "Busan Museum of Modern Art", description: "World-class contemporary art in the beach district", icon: "🖼️" },
          { time: "7:00 PM", activity: "Millak Waterside Park", description: "Seafood raw fish village with ocean sunset views", icon: "utensils" },
        ],
        accommodation: "Westin Chosun Busan",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 6,
        title: "Jeju Island – Volcanic Wonder",
        location: "Jeju Island",
        activities: [
          { time: "8:00 AM", activity: "Flight to Jeju", description: "45-min flight from Busan to Jeju Island", icon: "plane" },
          { time: "10:00 AM", activity: "Manjanggul Lava Tube", description: "Walk through one of the world's longest lava tubes (UNESCO)", icon: "🌋" },
          { time: "12:30 PM", activity: "Seongsan Ilchulbong", description: "Hike up the UNESCO sunrise peak — volcanic crater with ocean views", icon: "🌋" },
          { time: "3:00 PM", activity: "Jeju Haenyeo Women Divers", description: "Watch legendary Jeju women free divers emerge from the sea", icon: "🏊" },
          { time: "5:00 PM", activity: "O'Sulloc Tea Fields", description: "Walk through bright green tea plantations with Hallasan backdrop", icon: "coffee" },
          { time: "8:00 PM", activity: "Jeju Black Pork BBQ", description: "Famous Jeju black pork grilled tableside — a must-eat!", icon: "🐷" },
        ],
        accommodation: "Lotte Hotel Jeju",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 7,
        title: "Departure from Jeju",
        location: "Jeju Island",
        activities: [
          { time: "9:00 AM", activity: "Final Breakfast", description: "Last Korean breakfast with juk (rice porridge) and banchan", icon: "🍚" },
          { time: "10:00 AM", activity: "Jeju Markets", description: "Last-minute shopping at Dongmun Traditional Market", icon: "shopping-bag" },
          { time: "12:00 PM", activity: "Airport Transfer", description: "Transfer to Jeju International Airport", icon: "bus" },
          { time: "2:00 PM", activity: "Departure", description: "Fly home — kamsahamnida Korea!", icon: "plane" },
        ],
        accommodation: "",
        meals: ["Breakfast"],
      },
    ],
    comparison: [
      {
        provider: "WanderSouls",
        price: 49999,
        duration: "7D/6N",
        inclusions: ["6N Premium Hotels", "Daily Breakfast", "KTX Train", "Domestic Flight", "DMZ Tour", "Hanbok Experience", "Food Tour", "All Transfers"],
        rating: 4.8,
        reviewCount: 1124,
        departureDates: ["Jun 6", "Jun 20", "Jul 4", "Jul 18"],
        url: "#",
        badge: "Best Value",
      },
      {
        provider: "Veena World",
        price: 155000,
        duration: "7D/6N",
        inclusions: ["6N Standard Hotels", "Breakfast", "KTX Train", "No Domestic Flight", "DMZ Tour"],
        rating: 4.4,
        reviewCount: 567,
        departureDates: ["Jun 12", "Jul 3", "Aug 7"],
        url: "https://www.veenaworld.com/south-korea-tour-packages",
      },
      {
        provider: "MakeMyTrip",
        price: 125000,
        duration: "7D/6N",
        inclusions: ["6N Hotels", "Breakfast", "No Train", "2 Domestic Flights", "No DMZ", "Shared Transfers"],
        rating: 4.1,
        reviewCount: 1892,
        departureDates: ["Jun 1", "Jun 15", "Jul 10", "Aug 5"],
        url: "https://www.makemytrip.com/holidays-international/south-korea-tour-packages.html",
      },
    ],
    gallery: [
      "/gallery/south-korea/sk_palace.png",
      "/gallery/south-korea/sk_busan.png",
      "/gallery/south-korea/sk_jeju.png",
      "/gallery/south-korea/sk_hanok.png",
    ],
  },
];

export function getDestinationBySlug(slug: string): Destination | undefined {
  return destinations.find((d) => d.slug === slug);
}
