export interface DayActivity {
  time: string;
  activity: string;
  description: string;
  icon: string;
}

export interface ItineraryDay {
  day: number;
  title: string;
  location: string;
  activities: DayActivity[];
  accommodation: string;
  meals: string[];
}

export interface PackagePrice {
  provider: string;
  price: number;
  duration: string;
  inclusions: string[];
  rating: number;
  reviewCount: number;
  departureDates: string[];
  url: string;
  badge?: string;
}

export interface Destination {
  slug: string;
  name: string;
  country: string;
  flag: string;
  tagline: string;
  description: string;
  heroImage: string;
  duration: string;
  groupSize: string;
  difficulty: string;
  basePrice: number;
  highlights: string[];
  inclusions: string[];
  exclusions: string[];
  bestTime: string;
  itinerary: ItineraryDay[];
  comparison: PackagePrice[];
  gallery: string[];
  tags: string[];
  rating: number;
  reviewCount: number;
}

export const destinations: Destination[] = [
  {
    slug: "kerala",
    name: "Kerala",
    country: "India",
    flag: "🇮🇳",
    tagline: "God's Own Country",
    description:
      "Spend three days navigating the Kerala backwaters on a private houseboat, followed by guided walks through Munnar's high-altitude tea estates.",
    heroImage: "/gallery/kerala/IMG_7864.jpg",
    duration: "7 Days / 6 Nights",
    groupSize: "2–15 People",
    difficulty: "Easy",
    basePrice: 24999,
    rating: 4.8,
    reviewCount: 1247,
    bestTime: "October – March",
    tags: ["Backwaters", "Beaches", "Hill Stations", "Ayurveda"],
    highlights: [
      "Houseboat cruise on Alleppey backwaters",
      "Munnar tea estate walk",
      "Kathakali cultural show",
      "Kovalam beach sunset",
      "Periyar wildlife sanctuary",
      "Traditional Kerala fish curry cooking class",
    ],
    inclusions: [
      "6 nights accommodation (deluxe hotels + 1 night houseboat)",
      "Daily breakfast and dinner",
      "All transfers in AC vehicle",
      "Houseboat cruise (full day)",
      "English-speaking guide",
      "Periyar nature walk",
      "All entry fees",
    ],
    exclusions: [
      "Airfare / train tickets",
      "Personal expenses",
      "Travel insurance",
      "Lunch",
      "Tips and gratuities",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival in Kochi – Spice Capital",
        location: "Kochi",
        activities: [
          { time: "10:00 AM", activity: "Airport Pickup", description: "Meet & greet at Cochin International Airport", icon: "plane" },
          { time: "12:00 PM", activity: "Hotel Check-in", description: "Check in to your heritage hotel in Fort Kochi", icon: "hotel" },
          { time: "2:00 PM", activity: "Fort Kochi Walk", description: "Explore the iconic Chinese fishing nets, St. Francis Church & Mattancherry Palace", icon: "map" },
          { time: "6:30 PM", activity: "Kathakali Show", description: "Evening classical Kathakali dance performance", icon: "music" },
          { time: "8:00 PM", activity: "Kerala Dinner", description: "Traditional Kerala sadya served on banana leaf", icon: "utensils" },
        ],
        accommodation: "Brunton Boatyard Heritage Hotel, Kochi",
        meals: ["Dinner"],
      },
      {
        day: 2,
        title: "Munnar – The Tea Hills",
        location: "Munnar",
        activities: [
          { time: "8:00 AM", activity: "Breakfast & Departure", description: "Drive to Munnar through scenic Western Ghats (4 hrs)", icon: "bus" },
          { time: "12:30 PM", activity: "Cheeyappara Waterfalls", description: "Stop at the stunning cascading waterfalls", icon: "waves" },
          { time: "2:00 PM", activity: "Tea Museum", description: "Learn about Kerala's tea heritage at Tata Tea Museum", icon: "coffee" },
          { time: "4:00 PM", activity: "Tea Plantation Walk", description: "Guided walk through lush green tea estates", icon: "leaf" },
          { time: "7:30 PM", activity: "Sunset Viewpoint", description: "Watch the golden sunset over the misty mountains", icon: "sunset" },
        ],
        accommodation: "Windermere Estate, Munnar",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 3,
        title: "Thekkady – Wild Encounters",
        location: "Thekkady",
        activities: [
          { time: "7:00 AM", activity: "Morning Nature Walk", description: "Early morning bird watching in Eravikulam National Park", icon: "bird" },
          { time: "10:00 AM", activity: "Drive to Thekkady", description: "2.5 hour drive through spice country", icon: "bus" },
          { time: "1:30 PM", activity: "Spice Garden Tour", description: "Visit cardamom & pepper plantations with guided tour", icon: "leaf" },
          { time: "3:30 PM", activity: "Periyar Boat Ride", description: "Boat safari on Periyar Lake spotting wildlife", icon: "ship" },
          { time: "7:00 PM", activity: "Kalaripayattu Show", description: "Watch Kerala's ancient martial art performance", icon: "swords" },
        ],
        accommodation: "Spice Village, Thekkady",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 4,
        title: "Alleppey – Backwater Paradise",
        location: "Alleppey",
        activities: [
          { time: "9:00 AM", activity: "Drive to Alleppey", description: "3-hour scenic drive to the Venice of the East", icon: "bus" },
          { time: "12:30 PM", activity: "Houseboat Check-in", description: "Board your luxurious traditional Kerala houseboat (Kettuvallam)", icon: "ship" },
          { time: "1:30 PM", activity: "Backwater Cruise", description: "Float through tranquil backwaters, rice paddies, and villages", icon: "waves" },
          { time: "4:00 PM", activity: "Village Visit", description: "Stop at a local village, coir-making demonstration", icon: "home" },
          { time: "7:30 PM", activity: "Sunset Dinner", description: "Fresh seafood dinner on deck as the sun sets over the lagoon", icon: "utensils" },
        ],
        accommodation: "Luxury Houseboat, Alleppey Backwaters",
        meals: ["Breakfast", "Lunch", "Dinner"],
      },
      {
        day: 5,
        title: "Kovalam – Beach Bliss",
        location: "Kovalam",
        activities: [
          { time: "7:30 AM", activity: "Sunrise on the Backwaters", description: "Watch the magical sunrise over the water from your houseboat deck", icon: "sunset" },
          { time: "9:00 AM", activity: "Drive to Kovalam", description: "3.5 hour drive to the beach capital of Kerala", icon: "bus" },
          { time: "1:00 PM", activity: "Beach Time", description: "Relax on the crescent-shaped Kovalam beach", icon: "umbrella" },
          { time: "3:30 PM", activity: "Ayurvedic Massage", description: "Traditional Kerala Abhyanga full body massage (90 min)", icon: "flower" },
          { time: "7:00 PM", activity: "Seafood Dinner", description: "Fresh catch at a beachside restaurant with ocean view", icon: "fish" },
        ],
        accommodation: "Turtle Bay Beach Club, Kovalam",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 6,
        title: "Trivandrum – Culture & History",
        location: "Thiruvananthapuram",
        activities: [
          { time: "9:00 AM", activity: "Padmanabhaswamy Temple", description: "Visit one of India's richest and most sacred temples", icon: "landmark" },
          { time: "11:30 AM", activity: "Napier Museum", description: "Explore Kerala's art, natural history & tribal artifacts", icon: "building" },
          { time: "2:00 PM", activity: "Kuthiramalika Palace", description: "Tour the royal palace with 122 horse-shaped brackets", icon: "crown" },
          { time: "4:30 PM", activity: "Shankumugham Beach", description: "Walk along the beach with views of the sunset", icon: "sunset" },
          { time: "7:30 PM", activity: "Farewell Kerala Dinner", description: "Special goodbye dinner with cultural music performance", icon: "music" },
        ],
        accommodation: "The Leela Palace, Trivandrum",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 7,
        title: "Departure Day",
        location: "Thiruvananthapuram",
        activities: [
          { time: "8:00 AM", activity: "Final Breakfast", description: "Last Kerala breakfast with appam and stew", icon: "coffee" },
          { time: "10:00 AM", activity: "Hotel Check-out", description: "Check out and transfer to Trivandrum International Airport", icon: "hotel" },
          { time: "12:00 PM", activity: "Airport Drop", description: "Fond farewell and departure from God's Own Country", icon: "plane" },
        ],
        accommodation: "",
        meals: ["Breakfast"],
      },
    ],
    comparison: [
      {
        provider: "WanderSouls",
        price: 24999,
        duration: "7D/6N",
        inclusions: ["6N Deluxe Hotels + Houseboat", "Breakfast & Dinner", "AC Transfers", "Guide", "Entry Fees", "Ayurvedic Session"],
        rating: 4.8,
        reviewCount: 1247,
        departureDates: ["Jun 15", "Jul 1", "Jul 15", "Aug 1"],
        url: "#",
        badge: "Best Value",
      },
      {
        provider: "Veena World",
        price: 31500,
        duration: "7D/6N",
        inclusions: ["6N Standard Hotels + Houseboat", "Breakfast Only", "AC Transfers", "Guide"],
        rating: 4.3,
        reviewCount: 842,
        departureDates: ["Jun 20", "Jul 5", "Aug 10"],
        url: "https://www.veenaworld.com/india/kerala-tour-packages",
      },
      {
        provider: "MakeMyTrip",
        price: 28750,
        duration: "7D/6N",
        inclusions: ["6N Hotels", "Breakfast Only", "Shared Transfers", "No Guide"],
        rating: 4.1,
        reviewCount: 2103,
        departureDates: ["Jun 10", "Jun 25", "Jul 20", "Aug 5"],
        url: "https://www.makemytrip.com/holidays-india/kerala-travel-packages.html",
      },
    ],
    gallery: [
      "/gallery/kerala/IMG_7864.jpg",
      "/gallery/kerala/IMG_7973.jpg",
      "/gallery/kerala/IMG_7996.jpg",
      "/gallery/kerala/IMG_8009.jpg",
      "/gallery/kerala/IMG_8023.jpg",
    ],
  },
  {
    slug: "thailand",
    name: "Thailand",
    country: "Thailand",
    flag: "🇹🇭",
    tagline: "Land of Smiles",
    description:
      "Navigate Bangkok's local food markets with our resident guides, then fly south for five days of private boat charters around the Phi Phi islands.",
    heroImage: "/gallery/thailand/WatArun.jpg",
    duration: "8 Days / 7 Nights",
    groupSize: "2–20 People",
    difficulty: "Easy",
    basePrice: 39999,
    rating: 4.9,
    reviewCount: 2158,
    bestTime: "November – April",
    tags: ["Temples", "Beaches", "Street Food", "Nightlife", "Islands"],
    highlights: [
      "Grand Palace & Wat Phra Kaew",
      "Chiang Mai Night Bazaar & temples",
      "Elephant Nature Park encounter",
      "Phi Phi Islands speedboat tour",
      "Thai cooking class",
      "Floating Market",
    ],
    inclusions: [
      "7 nights accommodation (mix of Bangkok, Chiang Mai & Phuket)",
      "Daily breakfast",
      "All inter-city flights (BKK-CNX-HKT)",
      "Airport & hotel transfers",
      "English-speaking guide",
      "Phi Phi island tour",
      "Thai cooking class",
      "All entry fees",
    ],
    exclusions: [
      "International airfare",
      "Travel insurance",
      "Lunch and dinner",
      "Personal expenses",
      "Visa fees (if applicable)",
    ],
    itinerary: [
      {
        day: 1,
        title: "Welcome to Bangkok",
        location: "Bangkok",
        activities: [
          { time: "12:00 PM", activity: "Arrival & Hotel Check-in", description: "Arrive at Suvarnabhumi Airport, transfer to Sukhumvit hotel", icon: "plane" },
          { time: "3:00 PM", activity: "Wat Pho & Reclining Buddha", description: "Visit the iconic 46-metre gold reclining Buddha", icon: "landmark" },
          { time: "5:30 PM", activity: "Chao Phraya River Cruise", description: "Sunset cruise along the River of Kings", icon: "ship" },
          { time: "8:00 PM", activity: "Khao San Road & Street Food", description: "Explore the legendary backpacker street with amazing street food", icon: "utensils" },
        ],
        accommodation: "Chatrium Hotel Riverside Bangkok",
        meals: ["Dinner"],
      },
      {
        day: 2,
        title: "Bangkok – Temples & Markets",
        location: "Bangkok",
        activities: [
          { time: "8:00 AM", activity: "Grand Palace & Wat Phra Kaew", description: "Explore Thailand's most sacred site with the Emerald Buddha", icon: "crown" },
          { time: "11:00 AM", activity: "Floating Market", description: "Damnoen Saduak – colourful boats selling local produce", icon: "shopping-bag" },
          { time: "2:00 PM", activity: "Wat Arun", description: "Cross the river to the Temple of Dawn – breathtaking views", icon: "sunset" },
          { time: "5:00 PM", activity: "Chatuchak Weekend Market", description: "World's largest weekend market (over 15,000 stalls)", icon: "shopping-cart" },
          { time: "8:00 PM", activity: "Rooftop Bar", description: "Cocktails with Bangkok skyline views at Sky Bar", icon: "glass-water" },
        ],
        accommodation: "Chatrium Hotel Riverside Bangkok",
        meals: ["Breakfast"],
      },
      {
        day: 3,
        title: "Chiang Mai – Rose of the North",
        location: "Chiang Mai",
        activities: [
          { time: "7:00 AM", activity: "Flight to Chiang Mai", description: "1-hour domestic flight to Chiang Mai Airport", icon: "plane" },
          { time: "10:30 AM", activity: "Old City Walking Tour", description: "Explore the ancient moat-surrounded old city and Tha Phae Gate", icon: "map" },
          { time: "2:00 PM", activity: "Doi Suthep Temple", description: "Sacred hilltop temple with panoramic city views (climb 300 steps!)", icon: "landmark" },
          { time: "5:00 PM", activity: "Night Bazaar", description: "Shop for handicrafts, silks & silver at the famous night market", icon: "moon" },
          { time: "7:30 PM", activity: "Khantoke Dinner", description: "Traditional northern Thai dinner with classical dance show", icon: "music" },
        ],
        accommodation: "Dhara Dhevi Chiang Mai",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 4,
        title: "Elephant Sanctuary & Cooking Class",
        location: "Chiang Mai",
        activities: [
          { time: "8:30 AM", activity: "Elephant Nature Park", description: "Full morning at ethical elephant sanctuary – feed, bathe & walk with elephants", icon: "camera" },
          { time: "1:00 PM", activity: "Lunch & Market Visit", description: "Visit a local organic market to pick fresh ingredients", icon: "leaf" },
          { time: "3:00 PM", activity: "Thai Cooking Class", description: "Learn to cook 4 authentic Thai dishes with a local chef", icon: "chef-hat" },
          { time: "7:00 PM", activity: "Lantern Ceremony", description: "Release a Khom Loi sky lantern (seasonal)", icon: "lantern" },
        ],
        accommodation: "Dhara Dhevi Chiang Mai",
        meals: ["Breakfast", "Lunch"],
      },
      {
        day: 5,
        title: "Phuket – Island Paradise",
        location: "Phuket",
        activities: [
          { time: "8:00 AM", activity: "Flight to Phuket", description: "Domestic flight from Chiang Mai to Phuket Airport", icon: "plane" },
          { time: "11:30 AM", activity: "Patong Beach", description: "Spend the afternoon on Thailand's most famous beach", icon: "umbrella" },
          { time: "4:00 PM", activity: "Big Buddha", description: "Visit the 45-metre marble Buddha with sweeping island views", icon: "user" },
          { time: "7:00 PM", activity: "Bangla Road", description: "Explore Phuket's vibrant nightlife and street performances", icon: "tent" },
        ],
        accommodation: "Katathani Phuket Beach Resort",
        meals: ["Breakfast"],
      },
      {
        day: 6,
        title: "Phi Phi Islands Speedboat Tour",
        location: "Phi Phi Islands",
        activities: [
          { time: "8:00 AM", activity: "Speedboat to Phi Phi", description: "45-min speedboat ride to paradise islands", icon: "ship" },
          { time: "9:30 AM", activity: "Maya Bay", description: "Visit the famous 'The Beach' movie location (limited access)", icon: "tree-palm" },
          { time: "11:00 AM", activity: "Snorkelling", description: "Coral reefs with tropical fish in crystal waters", icon: "waves" },
          { time: "1:00 PM", activity: "Lunch on Phi Phi Don", description: "Fresh seafood BBQ on the beach", icon: "fish" },
          { time: "3:00 PM", activity: "Viking Cave & Monkey Bay", description: "Explore ancient Viking cave paintings and meet cheeky monkeys", icon: "camera" },
          { time: "5:00 PM", activity: "Return to Phuket", description: "Speedboat back to Phuket with sunset views", icon: "sunset" },
        ],
        accommodation: "Katathani Phuket Beach Resort",
        meals: ["Breakfast", "Lunch"],
      },
      {
        day: 7,
        title: "Phuket – Leisure & Spa",
        location: "Phuket",
        activities: [
          { time: "9:00 AM", activity: "Karon Beach", description: "Morning at the less crowded beautiful Karon Beach", icon: "waves" },
          { time: "12:00 PM", activity: "Thai Massage", description: "2-hour traditional Thai massage at a luxury spa", icon: "flower" },
          { time: "3:00 PM", activity: "Phuket Old Town", description: "Explore Sino-Portuguese architecture and colourful shophouses", icon: "home" },
          { time: "7:30 PM", activity: "Farewell Thai Dinner", description: "Premium Thai seafood dinner on the beach", icon: "fish" },
        ],
        accommodation: "Katathani Phuket Beach Resort",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 8,
        title: "Departure from Phuket",
        location: "Phuket",
        activities: [
          { time: "9:00 AM", activity: "Final Breakfast", description: "Last Thai breakfast at the resort", icon: "coffee" },
          { time: "11:00 AM", activity: "Check-out & Transfer", description: "Hotel check-out and transfer to Phuket International Airport", icon: "bus" },
          { time: "2:00 PM", activity: "Departure", description: "Board your international flight home, khob khun krap!", icon: "plane" },
        ],
        accommodation: "",
        meals: ["Breakfast"],
      },
    ],
    comparison: [
      {
        provider: "WanderSouls",
        price: 39999,
        duration: "8D/7N",
        inclusions: ["7N Premium Hotels", "Daily Breakfast", "3 Domestic Flights", "Island Tour", "Elephant Sanctuary", "Cooking Class", "All Transfers"],
        rating: 4.9,
        reviewCount: 2158,
        departureDates: ["Jun 12", "Jul 3", "Jul 17", "Aug 7"],
        url: "#",
        badge: "Most Popular",
      },
      {
        provider: "Veena World",
        price: 52499,
        duration: "8D/7N",
        inclusions: ["7N Standard Hotels", "Breakfast", "2 Domestic Flights", "Island Tour", "Transfers"],
        rating: 4.4,
        reviewCount: 1203,
        departureDates: ["Jun 18", "Jul 9", "Aug 2"],
        url: "https://www.veenaworld.com/thailand-tour-packages",
      },
      {
        provider: "MakeMyTrip",
        price: 47081,
        duration: "8D/7N",
        inclusions: ["7N Hotels", "Breakfast", "2 Domestic Flights", "No Island Tour", "Shared Transfers"],
        rating: 4.2,
        reviewCount: 3412,
        departureDates: ["Jun 5", "Jun 22", "Jul 10", "Aug 15"],
        url: "https://www.makemytrip.com/holidays-international/7nights-thailand-vacation-tour-package.html",
      },
    ],
    gallery: [
      "/gallery/thailand/AyutthayaElephant.jpg",
      "/gallery/thailand/mayabay.jpg",
      "/gallery/thailand/WatArun.jpg",
      "/gallery/thailand/reclining-buddha.jpg",
      "/gallery/thailand/wat-arun-2.jpg",
    ],
  },
  {
    slug: "malaysia",
    name: "Malaysia",
    country: "Malaysia",
    flag: "🇲🇾",
    tagline: "Truly Asia",
    description:
      "Explore the bustling street food and iconic Petronas Towers of Kuala Lumpur, followed by the misty mountain views of Genting Highlands and Chin Swee Caves.",
    heroImage: "/gallery/malaysia/chinsweecave.jpg",
    duration: "6 Days / 5 Nights",
    groupSize: "2–16 People",
    difficulty: "Easy",
    basePrice: 29999,
    rating: 4.8,
    reviewCount: 942,
    bestTime: "Year-round",
    tags: ["City", "Theme Parks", "Shopping", "Food"],
    highlights: [
      "Petronas Twin Towers & KLCC Park",
      "Batu Caves 272 colorful steps climbing",
      "Genting Highlands cable car ride",
      "Chin Swee Caves Temple exploration",
      "Jalan Alor street food tour",
    ],
    inclusions: [
      "5 nights deluxe accommodation",
      "Daily breakfast",
      "All transfers by private vehicle",
      "Genting cable car tickets",
      "Kuala Lumpur guided tour",
      "All entry fees",
    ],
    exclusions: [
      "International flights",
      "Travel insurance",
      "Lunch & dinner",
      "Personal expenses",
    ],
    itinerary: [
      {
        day: 1,
        title: "Welcome to Kuala Lumpur",
        location: "Kuala Lumpur",
        activities: [
          { time: "2:00 PM", activity: "Airport pickup & Check-in", description: "Arrive at KLIA, private transfer to city center hotel", icon: "plane" },
          { time: "5:00 PM", activity: "Petronas Twin Towers", description: "Photostop at the base of the world's tallest twin towers", icon: "building" },
          { time: "7:30 PM", activity: "Jalan Alor Food Tour", description: "Taste local specialties like grilled wings and satay at the night market", icon: "utensils" },
        ],
        accommodation: "Grand Hyatt Kuala Lumpur",
        meals: ["Dinner"],
      },
      {
        day: 2,
        title: "Batu Caves & KL City Tour",
        location: "Kuala Lumpur",
        activities: [
          { time: "9:00 AM", activity: "Batu Caves Expedition", description: "Climb the 272 rainbow-colored steps to the temple cave", icon: "mountain" },
          { time: "12:00 PM", activity: "KL City Sightseeing", description: "Visit Merdeka Square, Istana Negara Royal Palace & National Mosque", icon: "map" },
          { time: "4:00 PM", activity: "KL Tower Entrance", description: "Observation deck entry for panoramic city views", icon: "eye" },
        ],
        accommodation: "Grand Hyatt Kuala Lumpur",
        meals: ["Breakfast"],
      },
      {
        day: 3,
        title: "Genting Highlands Retreat",
        location: "Genting Highlands",
        activities: [
          { time: "8:30 AM", activity: "Drive to Genting", description: "Scenic drive towards the highlands", icon: "bus" },
          { time: "10:00 AM", activity: "Awana SkyWay Cable Car", description: "Glass-floor gondola ride through the clouds", icon: "ship" },
          { time: "11:00 AM", activity: "Chin Swee Caves Temple", description: "Explore the majestic multi-tiered pagoda on the cliff face", icon: "landmark" },
          { time: "2:00 PM", activity: "Genting Skytropolis", description: "Free time at the high-altitude indoor theme park", icon: "ticket" },
        ],
        accommodation: "First World Hotel, Genting Highlands",
        meals: ["Breakfast"],
      },
      {
        day: 4,
        title: "Kuala Lumpur Shopping & Culture",
        location: "Kuala Lumpur",
        activities: [
          { time: "10:00 AM", activity: "Chinatown & Central Market", description: "Browse traditional heritage shophouses and local handicrafts", icon: "shopping-bag" },
          { time: "2:00 PM", activity: "Bukit Bintang Mall Crawl", description: "Luxury shopping at Pavilion KL and surrounding centers", icon: "shopping-cart" },
          { time: "8:00 PM", activity: "Farewell Dinner", description: "Fine dining overlooking the illuminated Petronas Towers", icon: "utensils" },
        ],
        accommodation: "Grand Hyatt Kuala Lumpur",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 5,
        title: "Putrajaya Day Cruise",
        location: "Putrajaya",
        activities: [
          { time: "9:30 AM", activity: "Drive to Putrajaya", description: "Visit Malaysia's federal administrative center", icon: "bus" },
          { time: "10:30 AM", activity: "Putra Mosque & Lake Cruise", description: "See the famous pink mosque and take a traditional boat ride", icon: "ship" },
          { time: "3:00 PM", activity: "Leisure Afternoon", description: "Relax or do final packing", icon: "coffee" },
        ],
        accommodation: "Grand Hyatt Kuala Lumpur",
        meals: ["Breakfast"],
      },
      {
        day: 6,
        title: "Departure Day",
        location: "Kuala Lumpur",
        activities: [
          { time: "9:00 AM", activity: "Final Breakfast", description: "Enjoy a Malay breakfast of Nasi Lemak", icon: "coffee" },
          { time: "11:00 AM", activity: "Airport Transfer", description: "Check out and head to KLIA for your flight home", icon: "plane" },
        ],
        accommodation: "",
        meals: ["Breakfast"],
      },
    ],
    comparison: [
      {
        provider: "WanderSouls",
        price: 29999,
        duration: "6D/5N",
        inclusions: ["5N Premium Hotels", "Daily Breakfast & 2 Dinners", "Private Transfers", "Genting Cable Car Tickets", "KL Tower Entrance", "Guide"],
        rating: 4.8,
        reviewCount: 942,
        departureDates: ["Jun 18", "Jul 8", "Jul 28", "Aug 15"],
        url: "#",
        badge: "Editor's Choice",
      },
      {
        provider: "Veena World",
        price: 38500,
        duration: "6D/5N",
        inclusions: ["5N Standard Hotels", "Breakfast Only", "Shared Coach Transfers", "Cable Car tickets"],
        rating: 4.3,
        reviewCount: 512,
        departureDates: ["Jun 22", "Jul 15", "Aug 10"],
        url: "https://www.veenaworld.com/malaysia-tour-packages",
      },
      {
        provider: "MakeMyTrip",
        price: 34500,
        duration: "6D/5N",
        inclusions: ["5N Hotels", "Breakfast Only", "Shared Transfers", "No KL Tower entry"],
        rating: 4.1,
        reviewCount: 1042,
        departureDates: ["Jun 10", "Jun 24", "Jul 15", "Aug 5"],
        url: "https://www.makemytrip.com/holidays-international/malaysia-tour-packages.html",
      },
    ],
    gallery: [
      "/gallery/malaysia/chinsweecave.jpg",
      "/gallery/malaysia/malaysiagenting.jpg",
      "/gallery/malaysia/IMG_1518.JPG",
      "/gallery/malaysia/IMG_1542.JPG",
      "/gallery/malaysia/IMG_1543.JPG",
      "/gallery/malaysia/IMG_8979.JPG",
      "/gallery/malaysia/IMG_9121.JPG",
      "/gallery/malaysia/IMG_9141.JPG",
    ],
  },
  {
    slug: "singapore",
    name: "Singapore",
    country: "Singapore",
    flag: "🇸🇬",
    tagline: "The Lion City",
    description:
      "Four nights in the city center. We balance the main attractions with private food tours through the local hawker centers and early access to the Gardens by the Bay.",
    heroImage: "/gallery/singapore/singapore.jpg",
    duration: "5 Days / 4 Nights",
    groupSize: "2–20 People",
    difficulty: "Easy",
    basePrice: 54999,
    rating: 4.8,
    reviewCount: 1876,
    bestTime: "February – April",
    tags: ["City", "Food", "Shopping", "Architecture", "Culture"],
    highlights: [
      "Gardens by the Bay & Supertrees",
      "Marina Bay Sands SkyPark",
      "Sentosa Island & Universal Studios",
      "Hawker Centre food tour",
      "Little India & Chinatown",
      "Night Safari",
    ],
    inclusions: [
      "4 nights luxury hotel",
      "Daily breakfast",
      "MRT card (loaded)",
      "Gardens by the Bay tickets",
      "Night Safari tickets",
      "Universal Studios tickets",
      "City food tour",
      "Airport transfers",
    ],
    exclusions: [
      "International airfare",
      "Lunch & dinner (except food tour)",
      "Travel insurance",
      "Personal expenses",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival – Lion City Welcome",
        location: "Singapore",
        activities: [
          { time: "2:00 PM", activity: "Changi Airport Arrival", description: "Arrive at Changi — voted world's best airport. Explore Jewel waterfall!", icon: "plane" },
          { time: "4:00 PM", activity: "Hotel Check-in", description: "Check in to your Marina Bay luxury hotel", icon: "hotel" },
          { time: "6:00 PM", activity: "Marina Bay Sands SkyPark", description: "Sunset views from 57 floors up at the iconic infinity pool terrace", icon: "building" },
          { time: "8:00 PM", activity: "Spectra Light Show", description: "Free outdoor water and light spectacle at Marina Bay", icon: "sparkles" },
          { time: "9:00 PM", activity: "Clarke Quay", description: "Riverside dining and nightlife at Singapore's famous quayside", icon: "beer" },
        ],
        accommodation: "Marina Bay Sands Hotel",
        meals: ["Dinner"],
      },
      {
        day: 2,
        title: "Gardens, Culture & Heritage",
        location: "Singapore",
        activities: [
          { time: "9:00 AM", activity: "Gardens by the Bay", description: "Explore Cloud Forest, Flower Dome & the iconic Supertrees", icon: "leaf" },
          { time: "12:30 PM", activity: "Hawker Centre Food Tour", description: "Guided tour of Maxwell Food Centre — try 8+ signature dishes", icon: "utensils" },
          { time: "3:00 PM", activity: "Chinatown", description: "Buddha Tooth Relic Temple, heritage shophouses & souvenir shopping", icon: "lantern" },
          { time: "5:30 PM", activity: "Little India", description: "Colourful streets, garland stalls & the Sri Veeramakaliamman Temple", icon: "landmark" },
          { time: "8:00 PM", activity: "Arab Quarter", description: "Sultan Mosque & rooftop cocktails at Haji Lane", icon: "🕌" },
        ],
        accommodation: "Marina Bay Sands Hotel",
        meals: ["Breakfast", "Lunch"],
      },
      {
        day: 3,
        title: "Sentosa Island Adventure",
        location: "Sentosa Island, Singapore",
        activities: [
          { time: "9:00 AM", activity: "Universal Studios Singapore", description: "Full morning at USS – rides, shows & Hollywood adventures", icon: "ticket" },
          { time: "1:00 PM", activity: "Siloso Beach", description: "Afternoon at Sentosa's beach – swimming, volleyball, banana boats", icon: "umbrella" },
          { time: "4:00 PM", activity: "S.E.A. Aquarium", description: "One of the world's largest aquariums with 100,000+ marine animals", icon: "fish" },
          { time: "7:30 PM", activity: "Wings of Time", description: "Spectacular outdoor night show with water, laser & fireworks", icon: "sparkles" },
        ],
        accommodation: "Marina Bay Sands Hotel",
        meals: ["Breakfast"],
      },
      {
        day: 4,
        title: "Night Safari & Orchard Road",
        location: "Singapore",
        activities: [
          { time: "10:00 AM", activity: "Orchard Road Shopping", description: "Singapore's iconic 2.2km shopping paradise with 21 malls", icon: "shopping-bag" },
          { time: "1:00 PM", activity: "Botanic Gardens", description: "UNESCO World Heritage site – orchid garden & rainforest walk", icon: "flower" },
          { time: "4:00 PM", activity: "High Tea", description: "Quintessential Singapore afternoon high tea at Raffles Hotel", icon: "coffee" },
          { time: "7:30 PM", activity: "Night Safari", description: "World's first nocturnal zoo – see 2,500 animals under moonlight", icon: "camera" },
        ],
        accommodation: "Marina Bay Sands Hotel",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 5,
        title: "Final Morning & Departure",
        location: "Singapore",
        activities: [
          { time: "9:00 AM", activity: "Breakfast & Leisure", description: "Final breakfast and free time for last-minute shopping", icon: "coffee" },
          { time: "11:00 AM", activity: "Merlion Park", description: "Photo stop at Singapore's iconic Merlion statue", icon: "camera" },
          { time: "1:00 PM", activity: "Airport Transfer", description: "Transfer to Changi International Airport for departure", icon: "bus" },
        ],
        accommodation: "",
        meals: ["Breakfast"],
      },
    ],
    comparison: [
      {
        provider: "WanderSouls",
        price: 54999,
        duration: "5D/4N",
        inclusions: ["4N Marina Bay Sands Hotel", "Daily Breakfast", "All Attraction Tickets", "MRT Card", "Food Tour", "Airport Transfers"],
        rating: 4.8,
        reviewCount: 1876,
        departureDates: ["Jun 10", "Jun 24", "Jul 8", "Jul 22"],
        url: "#",
        badge: "Premium Pick",
      },
      {
        provider: "Veena World",
        price: 68499,
        duration: "5D/4N",
        inclusions: ["4N Standard Hotel", "Breakfast", "2 Attraction Tickets", "No Food Tour", "Airport Transfers"],
        rating: 4.5,
        reviewCount: 934,
        departureDates: ["Jun 15", "Jul 1", "Aug 5"],
        url: "https://www.veenaworld.com/singapore-tour-packages",
      },
      {
        provider: "MakeMyTrip",
        price: 52999,
        duration: "5D/4N",
        inclusions: ["4N Hotel", "Breakfast", "2 Attraction Tickets", "Shared Transfers"],
        rating: 4.2,
        reviewCount: 2841,
        departureDates: ["Jun 5", "Jun 19", "Jul 12", "Aug 2"],
        url: "https://www.makemytrip.com/singapore-tour-packages",
      },
    ],
    gallery: [
      "/gallery/singapore/singapore.jpg",
      "/gallery/singapore/SGfood.jpg",
      "/gallery/singapore/SGfood2.jpg",
      "/gallery/singapore/birdparkSG.jpg",
      "/gallery/singapore/universal.jpg",
      "/gallery/singapore/whatsapp-img-1.jpeg",
      "/gallery/singapore/whatsapp-img-2.jpeg",
      "/gallery/singapore/whatsapp-img-3.jpeg",
    ],
  },
  {
    slug: "meghalaya",
    name: "Meghalaya",
    country: "India",
    flag: "🇮🇳",
    tagline: "Abode of the Clouds",
    description:
      "Walk across the living root bridges of Cherrapunji, boat on the crystal clear waters of Umngot River in Dawki, and explore spectacular limestone caves.",
    heroImage: "/gallery/meghalaya/FullSizeRender.jpg",
    duration: "6 Days / 5 Nights",
    groupSize: "2–12 People",
    difficulty: "Moderate",
    basePrice: 19999,
    rating: 4.9,
    reviewCount: 752,
    bestTime: "October – May",
    tags: ["Nature", "Trekking", "Waterfalls", "Caves"],
    highlights: [
      "Living Root Bridges of Nongriat",
      "Boating on Dawki crystal clear river",
      "Cherrapunji waterfall trekking",
      "Mawsmai Limestone Caves exploration",
      "Mawlynnong cleanest village tour",
    ],
    inclusions: [
      "5 nights accommodation in boutique stays",
      "Daily breakfast and dinner",
      "All transfers in private SUV",
      "Dawki boating charges",
      "Local trekking guide",
    ],
    exclusions: [
      "Airfare to Guwahati",
      "Lunch & personal purchases",
      "Travel insurance",
    ],
    itinerary: [
      {
        day: 1,
        title: "Guwahati to Shillong – The Scotland of the East",
        location: "Shillong",
        activities: [
          { time: "11:00 AM", activity: "Guwahati pickup", description: "Meet & greet at Guwahati Airport and head to Shillong (3.5 hrs)", icon: "plane" },
          { time: "1:30 PM", activity: "Umiam Lake Boating", description: "Stop at the breathtaking Umiam Lake for speedboating", icon: "waves" },
          { time: "4:00 PM", activity: "Hotel Check-in", description: "Check in to your luxury boutique lake-facing cottage", icon: "hotel" },
          { time: "6:00 PM", activity: "Police Bazar Walk", description: "Explore the bustling local markets of Shillong", icon: "shopping-bag" },
        ],
        accommodation: "Ri Kynjai Serenity Lake Resort, Shillong",
        meals: ["Dinner"],
      },
      {
        day: 2,
        title: "Shillong City Tour & Drive to Cherrapunji",
        location: "Cherrapunji",
        activities: [
          { time: "9:00 AM", activity: "Elephant Falls", description: "Visit the three-step cascading waterfall", icon: "waves" },
          { time: "11:00 AM", activity: "Laitlum Canyons", description: "Breathtaking green canyons shrouded in rolling mist", icon: "mountain" },
          { time: "1:30 PM", activity: "Drive to Cherrapunji", description: "Scenic drive into one of the wettest places on earth", icon: "bus" },
        ],
        accommodation: "Polo Orchid Resort, Cherrapunji",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 3,
        title: "Double Decker Living Root Bridge Trek",
        location: "Cherrapunji",
        activities: [
          { time: "7:30 AM", activity: "Trek to Nongriat", description: "Guided descent down 3,000 steps into the forest", icon: "walk" },
          { time: "10:30 AM", activity: "Double Decker Root Bridge", description: "Marvel at the bio-engineered living tree root bridges", icon: "landmark" },
          { time: "12:00 PM", activity: "Rainbow Falls Trek", description: "Extend trek to see the rainbow hovering over blue pool", icon: "waves" },
        ],
        accommodation: "Polo Orchid Resort, Cherrapunji",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 4,
        title: "Cherrapunji Canyons & Mawsmai Caves",
        location: "Cherrapunji",
        activities: [
          { time: "9:00 AM", activity: "Mawsmai Limestone Caves", description: "Walk through illuminated natural limestone formations", icon: "landmark" },
          { time: "11:30 AM", activity: "Nohkalikai Waterfalls", description: "India's tallest plunge waterfall viewpoint", icon: "waves" },
          { time: "3:00 PM", activity: "Eco Park Visit", description: "Stroll along the edge of the Cherrapunji gorges", icon: "tree" },
        ],
        accommodation: "Polo Orchid Resort, Cherrapunji",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 5,
        title: "Dawki Boating & Mawlynnong Cleanest Village",
        location: "Dawki",
        activities: [
          { time: "8:00 AM", activity: "Drive to Mawlynnong", description: "Visit Asia's cleanest village and check the single root bridge", icon: "home" },
          { time: "11:30 AM", activity: "Dawki Umngot River Boating", description: "Boat ride on the crystal clear waters where boats look like they float in air", icon: "ship" },
          { time: "4:00 PM", activity: "Return to Shillong", description: "Drive back to Shillong for final evening", icon: "bus" },
        ],
        accommodation: "Ri Kynjai Serenity Lake Resort, Shillong",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 6,
        title: "Departure to Guwahati",
        location: "Guwahati",
        activities: [
          { time: "8:00 AM", activity: "Final Breakfast", description: "Enjoy a local breakfast of red rice and stew", icon: "coffee" },
          { time: "10:00 AM", activity: "Guwahati Airport Drop", description: "Transfer to airport for departure flight", icon: "plane" },
        ],
        accommodation: "",
        meals: ["Breakfast"],
      },
    ],
    comparison: [
      {
        provider: "WanderSouls",
        price: 19999,
        duration: "6D/5N",
        inclusions: ["5N Premium Boutique Resorts", "Daily Breakfast & Dinner", "Private SUV Transfers", "Dawki Boating", "Root Bridge Guide", "Entry Fees"],
        rating: 4.9,
        reviewCount: 752,
        departureDates: ["Jun 12", "Jun 28", "Jul 14", "Aug 10"],
        url: "#",
        badge: "Best Value",
      },
      {
        provider: "Veena World",
        price: 26500,
        duration: "6D/5N",
        inclusions: ["5N Standard Hotels", "Breakfast Only", "Shared Coach Transfers", "No Dawki boating"],
        rating: 4.4,
        reviewCount: 312,
        departureDates: ["Jun 18", "Jul 5", "Aug 12"],
        url: "https://www.veenaworld.com/india/meghalaya-tour-packages",
      },
      {
        provider: "MakeMyTrip",
        price: 23200,
        duration: "6D/5N",
        inclusions: ["5N Hotels", "Breakfast Only", "Shared Transfers", "No Nongriat Trek guide"],
        rating: 4.2,
        reviewCount: 541,
        departureDates: ["Jun 5", "Jun 19", "Jul 12", "Aug 2"],
        url: "https://www.makemytrip.com/holidays-india/meghalaya-travel-packages.html",
      },
    ],
    gallery: [
      "/gallery/meghalaya/FullSizeRender.jpg",
      "/gallery/meghalaya/IMG_8463.jpg",
      "/gallery/meghalaya/IMG_8531.jpg",
    ],
  },
  {
    slug: "bali",
    name: "Bali",
    country: "Indonesia",
    flag: "🇮🇩",
    tagline: "Island of the Gods",
    description:
      "Experience the perfect harmony of spiritual culture, lush rice terraces in Ubud, and private beach getaways in Nusa Dua.",
    heroImage: "/gallery/bali/tanah-lot.jpg",
    duration: "7 Days / 6 Nights",
    groupSize: "2–18 People",
    difficulty: "Easy",
    basePrice: 34999,
    rating: 4.8,
    reviewCount: 1954,
    bestTime: "April – October",
    tags: ["Beaches", "Temples", "Culture", "Islands"],
    highlights: [
      "Ubud Sacred Monkey Forest & swing",
      "Saraswati Temple traditional walk",
      "Tanah Lot temple cliff sunset views",
      "Nusa Penida manta ray snorkeling",
      "Tegenungan Waterfall trek",
    ],
    inclusions: [
      "6 nights premium hotel stay (Ubud & Seminyak)",
      "Daily breakfast",
      "All private AC vehicle transfers",
      "Nusa Penida speedboat roundtrip",
      "Local English-speaking guide",
    ],
    exclusions: [
      "International flights",
      "Visa on arrival fees",
      "Lunch & dinner",
      "Travel insurance",
    ],
    itinerary: [
      {
        day: 1,
        title: "Welcome to Bali",
        location: "Ubud",
        activities: [
          { time: "1:00 PM", activity: "Airport pickup & transfer", description: "Arrive at Ngurah Rai Airport, transfer to Ubud hotel", icon: "plane" },
          { time: "4:00 PM", activity: "Ubud Market", description: "Browse traditional art, textiles, and wood carvings", icon: "shopping-bag" },
          { time: "7:00 PM", activity: "Balinese Welcome Dinner", description: "Enjoy crispy duck and local satay lilit", icon: "utensils" },
        ],
        accommodation: "Alila Ubud Resort",
        meals: ["Dinner"],
      },
      {
        day: 2,
        title: "Ubud Culture & Bali Swing",
        location: "Ubud",
        activities: [
          { time: "9:00 AM", activity: "Sacred Monkey Forest", description: "See nutmeg forest and grey long-tailed macaques", icon: "camera" },
          { time: "11:30 AM", activity: "Tegallalang Rice Terraces", description: "Walk through iconic emerald rice paddies", icon: "leaf" },
          { time: "2:00 PM", activity: "Bali Swing Adventure", description: "Swing over the jungle canopy with river views", icon: "ticket" },
        ],
        accommodation: "Alila Ubud Resort",
        meals: ["Breakfast"],
      },
      {
        day: 3,
        title: "Waterfalls & Elephant Cave",
        location: "Ubud",
        activities: [
          { time: "9:00 AM", activity: "Tegenungan Waterfall", description: "Hike down to the base of the gushing jungle waterfall", icon: "waves" },
          { time: "11:30 AM", activity: "Goa Gajah Cave", description: "Explore the 9th-century Elephant Cave sanctuary", icon: "landmark" },
          { time: "3:00 PM", activity: "Saraswati Temple", description: "Stroll along the lotus-covered walkways of the water palace", icon: "flower" },
        ],
        accommodation: "Alila Ubud Resort",
        meals: ["Breakfast"],
      },
      {
        day: 4,
        title: "Nusa Penida Island Expedition",
        location: "Nusa Penida",
        activities: [
          { time: "7:30 AM", activity: "Speedboat to Nusa Penida", description: "Depart from Sanur beach on a speedboat", icon: "ship" },
          { time: "9:00 AM", activity: "Kelingking Beach View", description: "Stand atop the T-Rex shaped limestone cliff face", icon: "mountain" },
          { time: "11:30 AM", activity: "Angel's Billabong & Broken Beach", description: "See the natural volcanic infinity pool and archway", icon: "waves" },
          { time: "2:00 PM", activity: "Manta Ray Snorkeling", description: "Snorkel in crystal-clear water with giant manta rays", icon: "fish" },
        ],
        accommodation: "Alila Ubud Resort",
        meals: ["Breakfast", "Lunch"],
      },
      {
        day: 5,
        title: "Ulun Danu & Tanah Lot Sunset",
        location: "Seminyak",
        activities: [
          { time: "9:00 AM", activity: "Ulun Danu Beratan Temple", description: "Visit the iconic temple floating on Lake Beratan", icon: "landmark" },
          { time: "2:00 PM", activity: "Tanah Lot Temple", description: "Observe the sea temple perched on a wave-swept rock cliff", icon: "sunset" },
          { time: "5:00 PM", activity: "Transfer to Seminyak", description: "Drive to Seminyak beachfront luxury hotel", icon: "bus" },
        ],
        accommodation: "W Bali Seminyak",
        meals: ["Breakfast"],
      },
      {
        day: 6,
        title: "Leisure Beach Day & Balinese Spa",
        location: "Seminyak",
        activities: [
          { time: "10:00 AM", activity: "Beach relaxation", description: "Sunbathe, swim, or browse the Seminyak boutiques", icon: "umbrella" },
          { time: "3:00 PM", activity: "Balinese Body Massage", description: "Relax with a traditional 2-hour oil massage", icon: "flower" },
          { time: "7:30 PM", activity: "Farewell Seafood Dinner", description: "Enjoy a seafood BBQ dinner directly on Jimbaran beach", icon: "fish" },
        ],
        accommodation: "W Bali Seminyak",
        meals: ["Breakfast", "Dinner"],
      },
      {
        day: 7,
        title: "Departure Day",
        location: "Seminyak",
        activities: [
          { time: "9:00 AM", activity: "Final Breakfast", description: "Enjoy your final breakfast overlooking the ocean", icon: "coffee" },
          { time: "11:00 AM", activity: "Airport Transfer", description: "Private drop to Ngurah Rai Airport for your departure flight", icon: "plane" },
        ],
        accommodation: "",
        meals: ["Breakfast"],
      },
    ],
    comparison: [
      {
        provider: "WanderSouls",
        price: 34999,
        duration: "7D/6N",
        inclusions: ["6N Premium Resorts (Ubud & Seminyak)", "Daily Breakfast & 2 Dinners", "All Private Transfers", "Nusa Penida speedboating & snorkelling", "Balinese Massage", "Guide"],
        rating: 4.8,
        reviewCount: 1954,
        departureDates: ["Jun 15", "Jul 5", "Jul 25", "Aug 12"],
        url: "#",
        badge: "Best Value",
      },
      {
        provider: "Veena World",
        price: 46800,
        duration: "7D/6N",
        inclusions: ["6N Standard Hotels", "Breakfast Only", "Shared Transfers", "Attraction entry tickets"],
        rating: 4.4,
        reviewCount: 612,
        departureDates: ["Jun 20", "Jul 12", "Aug 18"],
        url: "https://www.veenaworld.com/indonesia/bali-tour-packages",
      },
      {
        provider: "MakeMyTrip",
        price: 42500,
        duration: "7D/6N",
        inclusions: ["6N Hotels", "Breakfast Only", "Shared transfers", "No Penida Snorkelling included"],
        rating: 4.1,
        reviewCount: 1542,
        departureDates: ["Jun 8", "Jun 22", "Jul 15", "Aug 1"],
        url: "https://www.makemytrip.com/holidays-international/bali-tour-packages.html",
      },
    ],
    gallery: [
      "/gallery/bali/Bali-swing.jpg",
      "/gallery/bali/Bali-zoo.jpg",
      "/gallery/bali/manta-express.jpg",
      "/gallery/bali/saraswati-temple.jpg",
      "/gallery/bali/tanah-lot.jpg",
      "/gallery/bali/teneguan-waterfall.jpg",
    ],
  },
];

export function getDestinationBySlug(slug: string): Destination | undefined {
  return destinations.find((d) => d.slug === slug);
}
